name: pruebas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - conda-forge::quarto
  - bioconda::integron_finder
  - bioconda::seqkit
  - bioconda::samtools
  - conda-forge::gcc  
  - conda-forge::make     
  - conda-forge::ncbi-datasets-cli
  - pandas
  - bioconda::skani
  - drep
  - openpyxl
  - blast
  - hmmsearch
  - conda-forge::matplotlib-venn