name: pruebas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - conda-forge::quarto
  - bioconda::integron_finder
  - bioconda::seqkit
  - bioconda::samtools
  - conda-forge::gcc  
  - conda-forge::make     
  - conda-forge::ncbi-datasets-cli
  - perl
  - perl-net-ssleay
  - perl-io-socket-ssl
  - pandas
  - conda-forge::openpyxl
  - bioconda::entrez-direct # para efetch
