# Import libraries 
import os
import subprocess 
import shlex 

# --------Definition of functions
#------------------------ Function to adapt the output of IntegronFinder2
def output_integronfinder(genome_acc, directory):
    """
    Searches the paths of the gbk files generated by IntegronFinder2.

    Args
    --------
    genome_acc (str): Accession name of the genome (to identify the folder). 
    directory (str): Path to the directory where the results are located.

    Returns
    --------
    gbk_files (list): List containing the full paths to the .gbk files.
    """
    gbk_files = [] # List to store the paths to the .gbk files
    # Identifies the specific directory where the results for that genome are located
    results_path = os.path.join(directory, f"Results_Integron_Finder_{genome_acc}")
    results = os.listdir(results_path) # Lists the files in the folder
    for each_result in results:
        if each_result.endswith(".gbk"):  # If it is a gbk file, its path is stored in the list
            gbk = os.path.join(results_path, each_result)
            gbk_files.append(gbk)
    return gbk_files

#------------------------ Function to execute IntegronFinder2
def Integron_Finder(genome_path, # Path to the genome
                    genome_acc, # Genome accession name
                    outdir,  # Output directory for the results
                    # Boolean arguments:
                    palindromes = False, # Keep palindromic versions (--keep-palindromes)
                    eagle_eyes = False, # More sensitive search argument (--eagle-eyes)
                    # Arguments with path value:
                    attc_model = None, # Another attC model to use (--attc-model ATTC_MODEL)
                    topology_file = None, # Path to the file with replicon topologies [--topology-file TOPOLOGY_FILE]
                    # Arguments with numerical value:
                    cpu = 1, # Number of CPUs to use (max 4 as recommended by integronfinder2) (--cpu)
                    distance_threshold = 4000, # Distance threshold, default in IntegronFinder is 4000 (--dt DISTANCE_THRESHOLD)
                    evalue_attc = 1, # E-value used to filter attC (--evalue-attc EVALUE_ATTC)
                    max_attc_size = 200, # Maximum attC site size (--max-attc-size MAX_ATTC_SIZE)
                    min_attc_size = 40, # Minimum attC site size (--min-attc-size MIN_ATTC_SIZE)
                    ): 
    """
    Executes IntegronFinder2 on an input genome with customizable parameters.

    Args
    -------
    genome_path (str): Full path to the input genome file.
    genome_acc (str): Accession name of the genome. 
    outdir (str): Path to the directory where the results will be saved.
    palindromes (bool, optional): Keeps the palindromic versions of the attC sites (--keep-palindromes). 
                                  Defaults to False.
    eagle_eyes (bool, optional): Reduces the noise threshold to search for hard-to-detect elements (--eagle-eyes). 
                                 Defaults to False.
    attc_model (str, optional): Path to an alternative covariance model for attC sites (--attc-model).
                                Defaults to None.
    topology_file (str, optional): Path to the file defining the topologies (circular/linear) of the replicons (--topology-file). 
                                   Defaults to None.
    cpu (int, optional): Number of CPU cores to use (max 4). 
                         Defaults to 1.
    distance_threshold (int, optional): Maximum distance in base pairs between two elements of an integron (-dt). 
                                        Defaults to 4000.
    evalue_attc (float or int, optional): E-value threshold to filter the found attC sites (--evalue-attc). 
                                          Defaults to 1.
    max_attc_size (int, optional): Maximum allowed size for an attC site (--max-attc-size). 
                                   Defaults to 200.
    min_attc_size (int, optional): Minimum allowed size for an attC site (--min-attc-size). 
                                   Defaults to 40.

    Return
    -------
    gbk_files (list): List of the resulting .gbk files after executing IntegronFinder2.
                      Returns None if an error occurs during execution.
    """
    # Set to 4 the max number of cpu
    if cpu > 4: cpu = 4
    # IntegronFinder2 command
    integronfinder_cmd = ["integron_finder", genome_path,
                          "--local-max", "--outdir", outdir, 
                          "--gbk", "--cpu", str(cpu), 
                          "-dt", str(distance_threshold),
                          "--evalue-attc", str(evalue_attc), 
                          "--max-attc-size", str(max_attc_size),
                          "--min-attc-size", str(min_attc_size)] 
    
    # Addition of boolean arguments:
    if palindromes:
        integronfinder_cmd.append("--keep-palindromes")
    if eagle_eyes:
        integronfinder_cmd.append("--eagle-eyes")

    # Addition of arguments with path value:
    if attc_model is not None:
        if not os.path.isfile(attc_model): # Check for correct path
            print(f"ttc_model not found: {attc_model}")
        else:
            integronfinder_cmd += ["--attc-model", attc_model]
        
    if topology_file is not None:
        if not os.path.isfile(topology_file): # Check for correct path
            print(f"topology_file not found: {topology_file}")
        else:
            integronfinder_cmd += ["--topology-file", topology_file]

    print(f"Executing: \n{shlex.join(integronfinder_cmd)}")
    try:
        subprocess.run(integronfinder_cmd, 
                       check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"Error executing IntegronFinder2:\n{e.stderr}")
        return None
        
    gbk_files = output_integronfinder(genome_acc, outdir)
    return gbk_files

