# Import libraries 
import subprocess 
import shlex
import os

############## Setup ----------------------------------------
# FIXME: Cuando acabe, hay que adaptar esto a cómo se encuentre finalmente!

current_dir = os.path.dirname(__file__) # __file__ has the path of the current .py 
HattCI_dir = os.path.join(current_dir, "T3_integronfiltering", "HattCI")

path_env_variable = os.environ["PATH"]

# Overwrite the PATH variable by adding the HattCI executable
sep = os.pathsep # PATH separator character for each operating system
os.environ["PATH"] = f"{HattCI_dir}{sep}{path_env_variable}" 
# By prepending the HattCI directory, it takes priority over any previously existing ones
#### PATH change only lasts while the script is running
############## ---------------------------------------------

# --------Definition of functions
#------------------------ Function to adapt the output of integron-filtering
def output_integronfiltering(outdir):
    """
    Finds and returns the path of the filtered FASTA file generated by integron_filtering.

    Args
    ------
    outdir (str): Path to the directory with the results of integron_filtering.

    Return:
    ------
    outfile (str): Path to the file with the results of integron_filtering.
    """
    # Files generated by integron_filtering
    results = os.listdir(outdir)
    for each_result in results:

        # The file with the genome with context ends in "attC_filtered.fasta"
        if each_result.endswith("attC_filtered.fasta"):
            # Complete path to the file
            outfile = os.path.join(outdir, each_result)
            if os.path.getsize(outfile) == 0: # Empty file means no integrons detected
                return None
            return outfile


def integron_filtering(genome_path, # Path to the genome
                       outdir, # Output directory for the results
                       covariance_model = os.path.join(current_dir, "T3_integronfiltering/attCs.cm"), # default, defined covariance model
                       cutoff_bit = 20, # bit score cut-off for the covariance model (default in the .sh)
                       min_bp = 500, # minimum size of the recognized sequence in base pairs (default in the .sh)
                       cpu = 1 # number of CPUs to use (default in the .sh)
                       ):
    """
    Executes the integron filtering script (attC-screening).

    Args
    ------
    genome_path (str): Path to the genome file to be processed.
    outdir (str): Output directory where the results will be saved.
    covariance_model (str, optional): Path to the covariance model file. 
                                      Defaults to 'T3_integronfiltering/attCs.cm'.
    cutoff_bit (int/float, optional): Bit score cut-off value for filtering. 
                                      Defaults to 20.
    min_bp (int, optional): Minimum size in base pairs of the recognized sequence. 
                            Defaults to 500.
    cpu (int, optional): Number of CPUs to use for the process. 
                         Defaults to 1.

    Return
    ------
    ruta_genoma_filtrado (str): The path to the generated filtered genome. 
                                If an error occurs, returns the original genome path (genome_path).
    """
    genome_path_abs = os.path.abspath(genome_path)
    outdir_abs = os.path.abspath(outdir)
    script_path = os.path.abspath("./scripts/pipeline_inicial/T3_integronfiltering/attC-screening.sh")

    # integron_filtering command 
    integronfiltering_cmd = [script_path, # path to the .sh
                             "-m", covariance_model, "-i", genome_path_abs, "-o", outdir_abs,
                              # Numbers must be a str
                             "-b", str(cutoff_bit), "-l", str(min_bp), "-t", str(cpu)]

    print(f"Executing: \n{shlex.join(integronfiltering_cmd)}")
    try:
        result = subprocess.run(integronfiltering_cmd, 
                       capture_output = True, text = True, check = True,
                       cwd = HattCI_dir)
    except subprocess.CalledProcessError as e:
        print(f"Error executing integron_filtering:\n{e.stderr}")
        return genome_path # Initial path
    # Function to adapt the path to the new filtered genome
    filtered_genome_path = output_integronfiltering(outdir)
    
    # Control to check correct generation of the file
    if not filtered_genome_path:
        print(f"Integron_filtering did not detect any integrons for: {genome_path}.")
        return None
    
    return filtered_genome_path
