project:
  type: book

book:
  title: "Diario Prácticas"
  chapters:
    - index.qmd
    - semana_01.qmd
    - semana_02.qmd
    - w_futuro.qmd

format:
  html:
    theme: cosmo
    code-line-numbers: true