---
title: "Semana del 21 al 25 de Septiembre"
number-sections: false
---

# Lunes 21/09

OBJETIVOS INICIALES:

- Dejar bien hecho scripts T3_3

- Aprender a paralelizar 

## Script T3_3_Pc.py

he dejado bien hecho (comentado + traducido) el script de extracción, búsqueda y clasificación de Pcs

[**FIXME**]{style="color: red;"}:
Aun así, Creo que da problemas porque detecta dos Pc como en la misma región¿ revisar eso -> igual con clustering se solcuionarlo

## Script T3_0_clusters 

Sigo sin poder hacer clustering ya que no me da el ordenador, probar ya con la workstation

# Martes 22/09

[**FIXME**]{style="color: red;"}:
Tengoq ue cambiar el código en la detección de promtoores porque, el P2 se encuentra justo en el final del gen de la integrasa, donde la att1
[Información Pc y P2](https://pmc.ncbi.nlm.nih.gov/articles/PMC3416418/)

In ∼10% of class 1 integrons, a second promoter (P2) is also present, created by the insertion of a GGG triplet within the attI1 recombination site that optimizes the spacing between the −35 and −10 boxes (from 14 nucleotides [nt] to 17 nt) (5). Usually, the presence of P2 compensates for the weak strength of Pc, enhancing gene cassette expression without interfering with the expression of the integrase gene (4, 5).

Altogether, more than 20 Pc-P2 combinations have been identified in class 1 integrons, regardless of their origin (5, 15). The most frequent configurations are as follows, according to their strength (5): 
PcW < PcW-P2 < PcH1 < PcH1-P2 < PcWTGN-10-P2 < PcWTGN-10 < PcH2 < PcS-P2 < PcS.

## REUNIÓN MODESTO+JOSE

1. Cambiar IF2 (mantenerlo a posteriori) por búsqueda vía HMM -> Hacer una optimización considerando: 

    - TIEMPO
    
    - SENSIBILIDAD. 

Hacerlo sobre dos datasets: *qeu estén ya descargados en el equipo

- Sobre un dataset de unos 6000 genomas (1000 de cada especie ESKAPEE por ejemplo¿ ***Incluir genomas con IS ++ ¿alguno Salmonella?). 

- Ídem en un dataset más pequeño para el principio

Comparar:

- A partir del genoma nt -> traducirlo -> búsqueda con perfil HMM (usa uno IF2 - creo que PF00589)

- Hacer un HMM de nt -> búsqueda

- Probar con HMM de prots más corto (ej. solo la parte inicial de la Integrasa)

- Probar con HMM de nt más corto (ej. solo la parte inicial de la Integrasa)

Con esto se hace un plot del E-value y se ve qué threshold tenemos que usar (vemos como el corte que vamos a poner en cada una de las opciones)
++++¿Mirar el E-value que usan IF2 e integron-filtering?



Para el TFM centrarnos en: clasificación de promotores + casettes + análisis biológico de resultados (introducir bioproyecos blablabla)

- Comprobar si en los metadatos está el ID del Bioproyecto

- OJO -> Hay que guardar el genoma entero si da + 


## Optimización BLAST con varios fragmentos

Jose me ha pasado la secuencia de la Integrasa y mediante la reverse_complement() he buscado y lo qeu tiene es un PcW
Por ello, le voy a quitar esos nt voy a poner ocmo N para que considere todos los posibles Promotores (y luego quiero fragmentar quitando la parte de los promotores)

Osea vamos a hacer blast con 3 query a nivel de nt:

- Seq de la int tal cual (tiene un PcW) (1014 pb)

- Seq de la Int entera (1014 pb) -> donde vamos a añadir N las posiciones que pueden variar en los Pc para que no afecte:

    - no aporta score positivo pero tampoco penaliza como mismatch real

- Seq de la Int sin la parte del promotor (y -100 pb upstream) (798 pb)

Script para generar los fasta: scripts/generate_Int1_fasta.py

## Tareas realizadas

He hecho varios scripts para poder  hacer la comparativa de optimización de tiempo / sensibilidad:

- generate_db.py: Para poder generar la  bbdd con x genomas de cada especie.

    - Para ello además he tenido que ir modificando el script T2_downloadgenomes.py, para poder introducir un número límite de genoams a descargar (que puede venir bein a futuro)

- generate_Int1_fasta.py: Para generar las secuencias de la Integrasa que se van a usar de query en BLAST

- optimization.py: Con diversas funciones que permiten realizar el blast y plottear los resultados

Aun así falta arreglar alguna parte de los FIXME dejados en el T2_downloadgenomes y solucionar el error del argumento out en generate_db()

# Miércoles 23/09

OBJETIVOS INICIALES:

- ¿preparar workstation?

- Solucionar los errores comentados del día anterior en los scripts T2 y generate_db()

- Evaluar como optimizar el tiempo con proteínas

## Script T2_downloadgenomes

He solucionado lo que pasaba que no se descargaban todos los accessions que le ponías en target_num (no le había pasado las flags a la función)

Además he termindo de comentar lo que quedaba

## Parte de optimización

He generado tres plots que se guardan en results/plots:

- Distribución de evaluates
- Distribución de BitScore
- Distribución de hits y unique_hits 

# Jueves 24/09

OBJETIVOS INICIALES

- Comentar bien generate_db() y acabar de definitr optimization

- Ejecutar ambos scripts para 1500 genomas de cada especie

- Evaluar la comparativa de tiempo con prots (aminoácidos)

- Empezar a paralelizar

## Script generate_db + optimization

Ambos scripts acabados y hecho el análisis en 1500 genomas de cada especie

## Comparativa a nivel de prots

Para comparar a nivel de proteínas vamos a usar tres estrategias:

- IF2

- Integron-filtering + IF2

(es inviable probarlo al mismo nivel en la bbdd con 7500 genomas)

¿igual probar en una base de datos más pequeña (ej. 100 genomas en total?)

he dejado los scripts preparados para hacer directamente el n_hits y n_hits_unique que encuentra -> probar mañana con bbdd más pequeña