---
title: "Semana del 14 al 18 de Septiembre"
number-sections: false
---

# Lunes 14/09

OBJETIVOS INICIAL HOY:

- Revisar bien los scripts hechos de la Tarea 3

- Revisar bien argumentos de cada uno de los programas usados (integron-filtering + integronfinder2)

- mirar bien lo del path para usar el .sh de integron-filtering

- ¿Generar el módulo de clasificación de los Pc? --> leer documentación sobre la secuencia de estos

## Problema con el integron-filtering

[**FIXME**]{style="color: red;"} 

Para que Integron-filtering funcione, requiere un binario externo (HattCI) en el PATH. Para solcuionarlo voy a adaptar la ruta al repositorio (ya que en teoría se debe instalar todo para que luego funcione el pipeline automatizado)
Añadido al script -> ./scripts/T3_0_integronfiltering.py

## IntegronFinder2

IntegronFinder2 identifica integrones en secuencias de DNA y acota las regiones de los Pc (que es lo que nos interesa) en los integrones encontrados

Uso del comando en bash:
```
integron_finder [-h] [--local-max] [--func-annot] [--cpu CPU] [-dt DISTANCE_THRESHOLD] 
                [--outdir OUTDIR] [--union-integrases] [--cmsearch CMSEARCH] 
                [--hmmsearch HMMSEARCH] [--prodigal PRODIGAL] [--path-func-annot PATH_FUNC_ANNOT] 
                [--gembase] [--gembase-path GEMBASE_PATH] [--annot-parser ANNOT_PARSER] 
                [--prot-file PROT_FILE] [--attc-model ATTC_MODEL] [--evalue-attc EVALUE_ATTC] 
                [--calin-threshold CALIN_THRESHOLD] [--keep-palindromes] [--no-proteins]
                [--promoter-attI] [--max-attc-size MAX_ATTC_SIZE] [--min-attc-size MIN_ATTC_SIZE] 
                [--eagle-eyes] [--pdf] [--gbk] [--keep-tmp] [--split-results] [--circ | --linear] 
                [--topology-file TOPOLOGY_FILE] [--version] [--mute] [-v] [-q] replicon
```

::: {.callout-important collapse="true"}
# Argumentos que acepta IntegronFinder2

*He marcado en azul aquellos argumentos que pueden tener sentido para la búsqueda y clasificación de Pcs:*

positional arguments:

- [**replicon**]{style="color: blue;"}: Path to the replicon file (in fasta format), eg : path/to/file.fst or file.fst

optional arguments:

- **-h, --help**: show this help message and exit

- [**--local-max**]{style="color: blue;"}: Allows thorough local detection (slower but more sensitive and do not increase false positive rate).

- **--func-annot**: Functional annotation of CDS associated with integrons HMM files are needed in Func_annot folder.
  
- [**--cpu CPU**]{style="color: blue;"}: Number of CPUs used by INFERNAL and HMMER. Increasing too much (usually above 4) may decrease performance. 

- [**-dt DISTANCE_THRESHOLD, --distance-thresh DISTANCE_THRESHOLD**]{style="color: blue;"}: Two elements are aggregated if they are distant of DISTANCE_THRESH [4000]bp or less
 
- [**--outdir OUTDIR**]{style="color: blue;"}: Set the output directory (default: current)

- **--union-integrases**: Instead of taking intersection of hits from Phage_int profile (Tyr recombinases) and integron_integrase profile,
                        use the union of the hits.
                        Es decir, IntegronFinder no detecta la Int con un solo modelo, sino combinando dos perfiles HMM distintos, luego se mantiene la intersección de ambos modelos para ser detectado

De estos siguientes no hay que modificar nada porque hemos instalado el entorno completo:

- **--cmsearch CMSEARCH**: Complete path to cmsearch if not in PATH. eg: /usr/local/bin/cmsearch

- **--hmmsearch HMMSEARCH**: Complete path to hmmsearch if not in PATH. eg: /usr/local/bin/hmmsearch

- **--prodigal PRODIGAL**: Complete path to prodigal if not in PATH. eg: /usr/local/bin/prodigal

- **--path-func-annot PATH_FUNC_ANNOT**: Path to file containing all hmm bank paths (one per line)

Los siguientes son alternativas para no usar PRODIGAL y usar otro fichero de proteínas ya anotado:

- **--gembase**: Use gembase formatted protein file instead of Prodigal. Folder structure must be preserved

- **--gembase-path GEMBASE_PATH**: path to the gembase root directory (needed only if the replicon file is not locatedin gembase-path)

- **--annot-parser ANNOT_PARSER**: the path to the parser to use to get information from protein file.

- **--prot-file PROT_FILE**: The path to the proteins file used for annotations

- [**--attc-model ATTC_MODEL**]{style="color: blue;"}: Path or file to the attc model (Covariance Matrix).

- [**--evalue-attc EVALUE_ATTC**]{style="color: blue;"}: Set evalue threshold to filter out hits above it (default: 1)
                                                          Un valor más bajo es más estricto (ahora es E-value)

- **--calin-threshold CALIN_THRESHOLD**: keep 'CALIN' only if attC sites number >= calin-threshold (default: 2)
                                        Un CALIN es un cluster de sitios attC que aparecen juntos sin una Int cercana asociada. El default exige que haya al menos 2 attC juntos para que sea CALIN

- [**--keep-palindromes**]{style="color: blue;"}: For a given hit, if the palindromic version is found, don't remove the one with highest evalue.
                          Los attC son repeticiones invertidas imperfectas, así que a veces se encuentran hits prácticamente en la misma posición en ambas hebras.
                          Por defecto, se queda solo con el mejor de los dos (menor e-value)
                          
- **--no-proteins**:  Don't annotate CDS and don't find integrase, just look for attC sites. 
                      No debemos usarlo porque anota el pc en relación a la posición de la Integrasas

- [**--promoter-attI**]{style="color: blue;"}: Search also for promoter and attI sites. (default False)

- [**--max-attc-size MAX_ATTC_SIZE**]{style="color: blue;"}: Set maximum value fot the attC size (default: 200bp)

- [**--min-attc-size MIN_ATTC_SIZE**]{style="color: blue;"}: Set minimum value fot the attC size (default: 40bp)

- [**--eagle-eyes]{style="color: blue;"}: Synonym of --local-max. Like a soaring eagle in the sky, catching rabbits (or attC sites) by surprise.

[### FIXME]{style="color: red;"}: Igual hay que modificar estos argumentos (topology file), porque:
como en la T2 controlamos el nivel de ensamblado (complete/chromosome/scaffold/contig) al descargar los genomas, podemos generar
el --topology-file con criterio correcto 
luego habría que añadir esta parte!!!

- **--circ**: Set the default topology for replicons to 'circular'

- **--linear**: Set the default topology for replicons to 'linear'

- [**--topology-file TOPOLOGY_FILE**]{style="color: blue;"}: The path to a file where the topology for each replicon is specified.

- **--version**: show program's version number and exit

- **--mute**: mute the log on stdout.(continue to log on integron_finder.out)

Output options:

- **--pdf**: For each complete integron, a simple graphic of the region is depicted (in pdf format)

- [**--gbk**]{style="color: blue;"}: generate a GenBank file with the sequence annotated with the same annotations than .integrons file.

- **--keep-tmp**: keep intermediate results. This results are stored in directory named tmp_<replicon id>

- **--split-results**: Instead of merging integron results from all replicon in one file, keep them in separated files.

- **-v, --verbose**: Increase verbosity of output (can be cumulative : -vv)

- **-q, --quiet**: Decrease verbosity of output (can be cumulative : -qq)

:::

Es decir, el nuevo uso del comando quedaría como:

```
integron_finder [--local-max] [--cpu CPU] [-dt DISTANCE_THRESHOLD] [--outdir OUTDIR] 
                [--attc-model ATTC_MODEL] [--evalue-attc EVALUE_ATTC] 
                [--keep-palindromes] --promoter-attI [--max-attc-size MAX_ATTC_SIZE] 
                [--min-attc-size MIN_ATTC_SIZE] [--eagle-eyes] --gbk 
                [--topology-file TOPOLOGY_FILE] replicon
```

### Output de IntegronFinder2

IntegronFinder2 genera diferentes outputs, pero como hemos puesto la opción **--gbk**, de este podemos extraer mucho más fácil la información
Por ello, usando SeqIO es fácil parsear el .gbk de forma directa

## PROBLEMA CON IntegronFinder2
[**FIXME**]{style="color: red;"} Por ahora, al extraer la secuencia, me obtiene todo P2 (mirandolo a ojo, sin módulo de clasificción)

MAÑANA: Voy a probar:

-  con otra especie,

-  probar hacineodlo sin la flag de filtering????

 y luego sino habrá que generar algún modulo de detección de promotores??? ver si existe????

# Martes 15/09

OBJETIVOS INICIAL

- hacer las pruebas de deteccion de promotores con: 

    a) otra especie u otro dataset

    b) sin la flag de filtering?

- tomar decision en base a los resultados obtenidos

- preparar tutoría 

RESULTADOS:
Con otras especies:
- con Acinetobacter baumannii solo detecta P2 también
- con Escherichia coli solo detecta P2 también

Con el flag de filtrado en false en esas dos especies ocurre lo mismo

¿Posible solución? -> En lugar de usar la flag de --promoter--attI extraer algo upstream de la región de integrón idenfiticada y ahí utilzar las secuencias teóricas de promotores para comprar directamente 

## Tutoría con Modesto

- Opción a conectarme vía VPN-UAM a un ordenador de su laboratorio si la workstation no conseguimos ponerla a punto

- Los umbrales para el filtrado de genomas los podemos sacar de papers de re-ensamblar y re-anotar genomas (ej. All the bacteria) --> Completeness y contaminacion

- Añadir un módulo para hacer un CLUSTERIZADO de genomas (al 99% o 95% de similitud, idealmente al 95% pero ir probando). Así nos quedamos con el genoma representativo y reducimos mucho la carga computacional en pasos posteriores

- Aprender sí o sí a PARALELIZAR en python. Por ejemplo, ir de 100 en 100 genomas: mientras los 100 primeros están rehidratandose, no pasa nada más, pero en los siguientes 100 genomas, mientras estos se rehidratan, los anteriores se están ya procesando (integron-filtering ect...)

- Añadido en a futuro, pero poder hacer un TIPADO DE GENOMAS, es decir, buscar la relación y poder clasificar el integrón por el tipo de genoma (ej. A,B,C,D en Ecoli // multilocus sequence: mls) --> ya hay programas que lo hacen (para relacionarlo con la literatura).

    - Esto se hace en entorno conda diferente ya que pueden estar desactualizados y puede dar problemas (coli phylogroups github // pyMLST github)

    - Así conseguimos evitar que la seleccción de genomas (ej. filtrado) sesgue los resultados que obtenemos

- Respecto a IF2: usar siempre --local-max; y probablemente haya que subir bastante el E-value (>1)

    - Además, la flag de identificar promotores como habíamos visto funciona fatal, entonces acotar directamente la región que interpreta como integron y buscar ahí con BLAST (NCBI en terminal) los prommotores (haciendo una bbdd teórica con los 13 promotores identificados)

    - El output podemos pedirselo en blast en una tabla que nos los ordena por los E-value (por ejemplo)

    - Preguntar a Jose si hay que trabajar con COMPLETOS o INCOMPLETOS (clasificación que da IF2) -> Modesto opina que mejor completos!!!!

- Revisar si los programas ya tienen checkpoints de parada -> si se para la ejecución del programa no hay ningún tipo de problema siempre que se indiqué qué ha fallado (si ya tienen los programas, no hacer otro checkpoint!)

- Si no se ha encontrado integron en el genoma -> se borran todos los datos (incluso el genoma entero descargado, lo de interon-filtering...) todo para liberar espacio

    - En relación con esto generar una tabla con los datos positivos y de ahí puedo coger el ID assembly (y esos al IF2 solo) -> TABLA SOLO CON LOS DATOS POSITIVOS

- para hacer esquemas de forma mucho más rápida podemos usar mermaid (GITHUB)

# Miércoles 16/09

OBJETIVOS INICIAL

- ir traduciendo el código desde el inicio

- cambiar los checkpoints que sobren

- añadir el módulo de clusterizado (se añade la función pero no tiene porqué ejecutarse siempre)

- leer sobre los umbrales de filtrado¿¿¿¿?

## Revisión de scripts

### Script 1: T1_Integrall_Pc_abundance.py

El script 1 (scripts/T1_Integrall_Pc_abundance.py) en teoría está ya acabado -> He modificado la función que había y la he dividido en 4:

- calcular la abundancia de Pc en todas las especies (lee .xlsx y calcula)

- calcular sobre la tabla de conteo para las espcies eskapee

- genera un .xlsx con la abundancia de ambas tablas

- genera los plots para ambas tablas


### Script 1: T2_downloadgenomes.py

Se han cambiado las métricas de calidad (se pueden introducir nuevas). Para fijar los valores default he utilizado el proyecto AllTheBacteria:
Indican que utilizan en su [documentacion](https://allthebacteria.org/docs/release_history/#:~:text=The%20defaults%20were%20used%20to%20define%20the,15Mbp.%20*%20Maximum%20number%20of%20contigs%202%2C000) los siguientes parámetros:

::: {.callout-note appearance="minimal" icon=false}

The species calls and high quality dataset are generated with the script make_hq_sample_list.py. 
The high quality dataset has 1,858,610 samples.

This script is updated since version 0.1 to expose all parameters to the user, so it can be rerun with different cutoffs. 
The defaults were used to define the high quality dataset here, which meant a sample must pass all of these requirements to be included as high quality:

- Have a sylph call with at least 99 percent minimum abundance. 

- If a sample has more than one call (eg where it has more than one run), then require all species calls to be the same

- Minimum checkm2 completeness of 90%

- Maximum checkm2 contamination of 5%

- Total assembly length between 100kbp and 15Mbp

- Maximum number of contigs 2,000

- Minimum N50 2,000
:::

[**#### FIXME**]{style="color: red;"} --> se pueden añadir entonces más métricas basandonos en este proyecto (sylph call, more than one call..., total assembly length, max num of contigs...)

Para descargar el script, desde la [web](https://osf.io/xv7q9/overview) > Files Preview > Metadata > make_hq_sample_list.py

Además, en el script, si no hay checkm info, se analiza también ese acc, así que procedo de la misma forma

Luego:

- he traducido completamente el script y limpiado el main code de abajo

- he quitado los chekcpoints que había introducido manualmente para que se usen directamente los del comadno datasets (he miardo y están bastgante bien explicados)

- he añadido los umbrales indicados en AllTheBacteria

Para añadir el módulo de clusterización:

### Clusterización de genomas

Para hacer la clusterización de genomas tiene que ser POSTERIOR a la descarga de los genomas (--rehydrate) y vamos a probar la herramienta skani:

[Skani](https://github.com/bluenote-1577/skani) permite calcular ANI (average nucleotide identity) y AF (aligned fraction) para secuencias.
>> Lo vamos a usar ya que es mucho más rápido que los BLAST-based y casi igual de precisos


ADEMÁS, vamos a utlizar la herramienta [dRep](https://github.com/MrOlm/drep) que utliza este algoritmo de skani y lo que hace es...

Lo introducimos en el .yml del entorno conda y creamos un nuevo archivo para clsuterizar (previo a integron-filtering), pero usamos ya las funciones creadas en el T3 entero.

```
dRep dereplicate [-p PROCESSORS] [-d] [-h] [-g [GENOMES ...]] [-l LENGTH] [-comp COMPLETENESS] 
                 [-con CONTAMINATION] [--ignoreGenomeQuality] [--genomeInfo GENOMEINFO]
                 [--checkM_method {lineage_wf,taxonomy_wf}] [--set_recursion SET_RECURSION] 
                 [--checkm_group_size CHECKM_GROUP_SIZE] [--S_algorithm {ANIn,goANI,skani,gANI,fastANI,ANImf}]
                 [-ms MASH_SKETCH] [--SkipMash] [--SkipSecondary] [--skani_extra SKANI_EXTRA] 
                 [--n_PRESET {normal,tight}] [-pa P_ANI] [-sa S_ANI] [-nc COV_THRESH] [-cm {total,larger}]
                 [--clusterAlg {single,ward,complete,weighted,average,centroid,median}] [--low_ram_primary_clustering] 
                 [--multiround_primary_clustering] [--primary_chunksize PRIMARY_CHUNKSIZE] 
                 [--greedy_secondary_clustering] [--run_tertiary_clustering] [-comW COMPLETENESS_WEIGHT] 
                 [-conW CONTAMINATION_WEIGHT] [-strW STRAIN_HETEROGENEITY_WEIGHT] [-N50W N50_WEIGHT] 
                 [-sizeW SIZE_WEIGHT] [-centW CENTRALITY_WEIGHT] [-extraW EXTRA_WEIGHT_TABLE] [--gen_warnings]
                 [--warn_dist WARN_DIST] [--warn_sim WARN_SIM] [--warn_aln WARN_ALN] [--skip_plots]
                 work_directory
```

::: {.callout-important collapse="true"}
# Argumentos que acepta dRep

*He marcado en azul aquellos argumentos que pueden tener sentido para la búsqueda y clasificación de Pcs:*

positional arguments:

- [**work_directory**]{style="color: blue;"}: Directory where data and output are stored    *** USE THE SAME WORK DIRECTORY FOR ALL DREP OPERATIONS ***

SYSTEM PARAMETERS:

- [**-p PROCESSORS, --processors PROCESSORS**]{style="color: blue;"}: threads (default: 6)

- **-d, --debug**: make extra debugging output (default: False)
- **-h, --help**: show this help message and exit

GENOME INPUT:

- [**-g [GENOMES ...], --genomes [GENOMES ...]**]{style="color: blue;"}: genomes to filter in .fasta format. 
                                                      Can also input a text file with paths to genomes, which results in fewer OS issues than wildcard expansion (default: None)

GENOME FILTERING OPTIONS:

- [**-l LENGTH, --length LENGTH**]{style="color: blue;"}: Minimum genome length (default: 50000) -> habría que añadirlo si usamosc ontigs o scaffolds pro si acaso

- [**-comp COMPLETENESS, --completeness COMPLETENESS**]{style="color: blue;"}: Minimum genome completeness (default: 75)

- [**-con CONTAMINATION, --contamination CONTAMINATION**]{style="color: blue;"}:  Maximum genome contamination (default: 25)

GENOME QUALITY ASSESSMENT OPTIONS:

[**FIXME**]{style="color: red;"}: En teoría nosotros ya limpiamos los genomas por checkM info (si se habilita la flag) PERO no conviene mezclar información de lNCBI.
Así que vamos a intentar correr externamente CheckM2 y de ahí pasarle la información a dRep

- **--ignoreGenomeQuality**: Don't run checkM or do any quality filtering. NOT RECOMMENDED! This is useful for use with bacteriophages or eukaryotes or things where checkM scoring does not work. 
                              Will only choose genomes based on length and N50 (default: False)
                              NO vamos a usarlo

- **--genomeInfo GENOMEINFO**: location of .csv file containing quality information on the genomes. 
                                Must contain: ["genome"(filename of .fasta file of that genome, including extension e.g. genome.fasta), 
                                "completeness"(0-100 value for completeness of the genome), "contamination"(0-100 value of the contamination of the genome)] (default: None)

- **--checkM_method {lineage_wf,taxonomy_wf}**: Either lineage_wf (more accurate) or taxonomy_wf (faster) (default: lineage_wf)

- **--set_recursion SET_RECURSION**: Increases the python recursion limit. NOT RECOMMENDED unless checkM is crashing due to recursion issues. 
                                    Recommended to set to 2000 if needed, but setting this could crash python (default: 0)

- **--checkm_group_size CHECKM_GROUP_SIZE**: The number of genomes passed to checkM at a time. Increasing this increases RAM but makes checkM faster (default: 2000)

GENOME COMPARISON OPTIONS:

- [**--S_algorithm {ANIn,goANI,skani,gANI,fastANI,ANImf}**]{style="color: blue;"}: Algorithm for secondary clustering comaprisons:
                                                                                    fastANI = Kmer-based approach; very fast
                                                                                    **skani** = Even faster Kmer-based approacht
                                                                                    ANImf   = (DEFAULT) Align whole genomes with nucmer; filter alignment; compare aligned regions
                                                                                    ANIn    = Align whole genomes with nucmer; compare aligned regions
                                                                                    gANI    = Identify and align ORFs; compare aligned ORFS
                                                                                    goANI   = Open source version of gANI; requires nsmimscan
                                                                                    (default: fastANI)

- **-ms MASH_SKETCH, --MASH_sketch MASH_SKETCH**: MASH sketch size (default: 1000)

- **--SkipMash**: Skip MASH clustering, just do secondary clustering on all genomes (default: False)

- **--SkipSecondary**: Skip secondary clustering, just perform MASH clustering (default: False)

- [**--skani_extra SKANI_EXTRA**]{style="color: blue;"}: Extra arguments to pass to skani triangle (default: )

- **--n_PRESET {normal,tight}**: Presets to pass to nucmer
                                  tight   = only align highly conserved regions
                                  normal  = default ANIn parameters (default: normal)

GENOME CLUSTERING OPTIONS:

- **-pa P_ANI, --P_ani P_ANI**: ANI threshold to form primary (MASH) clusters (default: 0.9)

- [**-sa S_ANI, --S_ani S_ANI**]{style="color: blue;"}: ANI threshold to form secondary clusters (default: 0.95)

- [**-nc COV_THRESH, --cov_thresh COV_THRESH**]{style="color: blue;"}: Minmum level of overlap between genomes when doing secondary comparisons (default: 0.1)

- **-cm {total,larger}, --coverage_method {total,larger}**: Method to calculate coverage of an alignment
                                                            (for ANIn/ANImf only; gANI and fastANI can only do larger method)
                                                            total   = 2*(aligned length) / (sum of total genome lengths)
                                                            larger  = max((aligned length / genome 1), (aligned_length / genome2))
                                                            (default: larger)

- **--clusterAlg {single,ward,complete,weighted,average,centroid,median}**: Algorithm used to cluster genomes (passed to scipy.cluster.hierarchy.linkage (default: average)

- [**--low_ram_primary_clustering**]{style="color: blue;"}: Use a memory-efficient algorithm for primary clustering. 
                                                            This only affects primary clustering and not secondary clustering. (default: False)

GREEDY CLUSTERING OPTIONS
These decrease RAM use and runtime at the expense of a minor loss in accuracy.

Recommended when clustering 5000+ genomes:

- [**--multiround_primary_clustering**]{style="color: blue;"}: Cluster each primary clunk separately and merge at the end with single linkage. 
                                                                Decreases RAM usage and increases speed, and the cost of a minor loss in precision and the
                                                                inability to plot primary_clustering_dendrograms. 
                                                                Especially helpful when clustering 5000+ genomes. 
                                                                Will be done with single linkage clustering (default: False)

- [**--primary_chunksize PRIMARY_CHUNKSIZE**]{style="color: blue;"}: Impacts multiround_primary_clustering. 
                                                                    If you have more than this many genomes, process them in chunks of this size. 
                                                                    (default: 5000)

- **--greedy_secondary_clustering**: Use a heuristic to avoid pair-wise comparisons when doing secondary clustering. 
                                     Will be done with single linkage clustering. 
                                     Only works for fastANI S_algorithm option at the moment (default: False) -> NO para skani

- [**--run_tertiary_clustering**]{style="color: blue;"}: Run an additional round of clustering on the final genome set. 
                                                          This is especially useful when greedy clustering is performed and/or to handle cases where similar genomes
                                                          end up in different primary clusters. 
                                                          Only works with dereplicate, not compare. (default: False)

SCORING CRITERIA
Based off of the formula: 
A*Completeness - B*Contamination + C*(Contamination * (strain_heterogeneity/100)) + D*log(N50) + E*log(size) + F*(centrality - S_ani)

A = completeness_weight; B = contamination_weight; C = strain_heterogeneity_weight; D = N50_weight; E = size_weight; F = cent_weight:

- **-comW COMPLETENESS_WEIGHT, --completeness_weight COMPLETENESS_WEIGHT**: completeness weight (default: 1)

- **-conW CONTAMINATION_WEIGHT, --contamination_weight CONTAMINATION_WEIGHT**: contamination weight (default: 5)

- **-strW STRAIN_HETEROGENEITY_WEIGHT, --strain_heterogeneity_weight STRAIN_HETEROGENEITY_WEIGHT**:  strain heterogeneity weight (default: 1)

- **-N50W N50_WEIGHT, --N50_weight N50_WEIGHT**: weight of log(genome N50) (default: 0.5)

- **-sizeW SIZE_WEIGHT, --size_weight SIZE_WEIGHT**: weight of log(genome size) (default: 0)

- **-centW CENTRALITY_WEIGHT, --centrality_weight CENTRALITY_WEIGHT**: Weight of (centrality - S_ani) (default: 1)

- **-extraW EXTRA_WEIGHT_TABLE, --extra_weight_table EXTRA_WEIGHT_TABLE**: Path to a tab-separated file with two-columns, no headers, listing genome and extra score to apply to that genome (default: None)

WARNINGS:

- **--gen_warnings**:        Generate warnings (default: False)

- **--warn_dist WARN_DIST**:   How far from the threshold to throw cluster warnings (default: 0.25)

- **--warn_sim WARN_SIM**:   Similarity threshold for warnings between dereplicated genomes (default: 0.98)

- **--warn_aln WARN_ALN**:   Minimum aligned fraction for warnings between dereplicated genomes (ANIn) (default: 0.25)

ANALYZE:

- [**--skip_plots**]{style="color: blue;"}: Dont make plots (default: False)

Example: dRep dereplicate output_dir/ -g /path/to/genomes/*.fasta

:::

Es decir, el nuevo uso del comando quedaría como:

```
dRep dereplicate [-p PROCESSORS] [-g [GENOMES ...]] [-l LENGTH] [-comp COMPLETENESS] 
                 [-con CONTAMINATION] [--genomeInfo GENOMEINFO]
                 [--S_algorithm {ANIn,goANI,skani,gANI,fastANI,ANImf}]
                 [--skani_extra SKANI_EXTRA] [-sa S_ANI] [-nc COV_THRESH] 
                 [--low_ram_primary_clustering] [--multiround_primary_clustering] 
                 [--primary_chunksize PRIMARY_CHUNKSIZE] 
                 [--run_tertiary_clustering] [--skip_plots] work_directory
```


Me está dando problemas el dRep ya que me consume toda la RAM creo???
He añadido flags para ver si funciona mejor (al menos en este ordenador), pero aunque sea para poder adaptar el código al resultado que dé.
Ej: [--low_ram_primary_clustering] [--multiround_primary_clustering] [--primary_chunksize PRIMARY_CHUNKSIZE] [--greedy_secondary_clustering] [--run_tertiary_clustering]  [--skip_plots]

Probar lo primero mañana ver si lo consigo aunuqe sea

He empezdo a traducir el T3 pero aun así creo que no se ha guardado

>> Como algoritmo vamos a usar skani y antes para la info de CheckM para seleccionar el genoma dentro de los que se parecen -> CheckM2

# Jueves 17/09

OBJETIVOS INICIAL:
Intentar arreglar lo de dRep y conseguir clusterizar
Seguir traduciendo y adaptando T3 - (borrar la parte de extraer Pcs...)
empezar a aprender a paralelizar?

He probado a ejectuar el script de clustering con la opción: "--ignoreGenomeQuality"; y ahí sí consigo ejecutarlo.
Hay que revisar bien las opciones que dejo finalmente para que clusterice bien.

## CheckM2

Voy a mirar para ejecutar primero [CheckM2](https://github.com/chklovski/CheckM2) y meterle la información por un .csv vía "--genomeInfo"

Información de CheckM2:

                ...::: CheckM2 v1.1.0 :::...

  General usage:

    predict         -> Predict the completeness and contamination of genome bins in a folder. Example usage: 

        checkm2 predict --threads 30 --input <folder_with_bins> --output-directory <output_folder>
    
    testrun         -> Runs Checkm2 on internal test genomes to ensure it runs without errors. Example usage: 

         checkm2 testrun --threads 10
    
    database        -> Download and set up required CheckM2 DIAMOND database for annotation

  Use checkm2 <command> -h for command-specific help.

```
checkm2 predict [-h] [--debug] [--version] [--quiet] [--lowmem] --input INPUT [INPUT ...] 
                --output-directory OUTPUT_DIRECTORY [--general] [--specific] [--allmodels] 
                [--genes] [-x EXTENSION] [--tmpdir TMPDIR] [--force] [--resume] 
                [--threads num_threads] [--stdout] [--remove_intermediates] [--ttable ttable] 
                [--database_path DATABASE_PATH] [--dbg_cos] [--dbg_vectors]
```

::: {.callout-important collapse="true"}
# Argumentos que acepta checkm2

*He marcado en azul aquellos argumentos que pueden tener sentido para la búsqueda y clasificación de Pcs:*

Predict the completeness and contamination of genome bins in a folder. Example usage: 

        checkm2 predict --threads 30 --input <folder_with_bins> --output-directory <output_folder>

options:

- **-h, --help**: show this help message and exit

- **--debug**: output debug information

- **--version**: output version information and quit

- **--quiet**: only output errors

- [**--lowmem**]{style="color: blue;"}:   Low memory mode. 
                            Reduces DIAMOND blocksize to significantly reduce RAM usage at the expense of longer runtime

required arguments:

- [**--input INPUT [INPUT ...], -i INPUT [INPUT ...]**]{style="color: blue;"}: Path to folder containing MAGs or list of MAGS to be analyzed
  
- [**--output-directory OUTPUT_DIRECTORY, --output_directory OUTPUT_DIRECTORY, -o OUTPUT_DIRECTORY**]{style="color: blue;"}:  
                        Path output to folder

additional arguments:

- **--general**: Force the use of the general quality prediction model (gradient boost)

- **--specific**: Force the use of the specific quality prediction model (neural network)

- **--allmodels**: Output quality prediction for both models for each genome.

- **--genes**: Treat input files as protein files. [Default: False]

- [**-x EXTENSION, --extension EXTENSION**]{style="color: blue;"}: Extension of input files. [Default: .fna]

- **--tmpdir TMPDIR**: specify an alternative directory for temporary files

- [**--force**]{style="color: blue;"}: overwrite output directory [default: do not overwrite]

- **--resume**: Reuse Prodigal and DIAMOND results found in output directory [default: not set]
 
- [**--threads num_threads, -t num_threads**]{style="color: blue;"}: number of CPUS to use [default: 1]
 
- **--stdout**: Print results to stdout [default: write to file]
 
- [**--remove_intermediates**]{style="color: blue;"}: Remove all intermediate files (protein files, diamond output) [default: don't]
 
- **--ttable ttable**: Provide a specific progidal translation table for bins [default: automatically determine either 11 or 4]
 
- **--database_path DATABASE_PATH**: Provide a location for the CheckM2 database for a given predict run [default: use either internal path set via <checkm2 database> or CHECKM2DB environmental variable]
  
- **--dbg_cos**: DEBUG: write cosine similarity values to file [default: don't]
 
- **--dbg_vectors**: DEBUG: dump pickled feature vectors to file [default: don't]

:::

Entonces el uso queda tal que:

```
checkm2 predict [--lowmem] --input INPUT [INPUT ...] [--force]
                --output-directory OUTPUT_DIRECTORY 
                [-x EXTENSION] [--threads num_threads] [--remove_intermediates] 
```

he acabdo el script de T3_0_clusters.py para poder clusterizar (primero hacer CheckM2 para obtener info + dRep)

## IntegronFinder2 + BLAST

Voy a intentar extraer la parte del integron y empezar a hacer la bbdd de blast para empezar a clasificar los Pc

Hay que hacer cambios en los argumentos que usa IntegronFinder2 tras la tutoría con Modesto.

- Por un lado, --local-max debe ir siempre obligatorio

- Además, como ya no vamos a extraer el Pc que encuentra IF2 sino que vamos a acotar directamente la región, vamos a eliminar el flag de --promoter

> Voy a probar a extraer la secuenica del integrón entera (con 100 pb upstream) y ahí hacer blast

# Viernes 18/09

Acabar de extraer bien la secuencia de Pc

hacer blast generando una bbdd con los promotores???

Empezar a aprender a paralelizar

## BLAST

Para utilizar [blast](https://github.com/evanpeikon/BLAST), primero hay que crear la base de datos de referencia:

```
makeblastdb -in ABP49492.fasta -dbtype prot -out ABP49492_db
```

Una vez generado el .fasta con las secuencias de promotores encontradas del [artículo](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1000793)
vamos a  hacer que ahga el blast

PERO hay qeu cambiar comandos porque el Pc es una región muy pequeña:

```
  blastn [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
    [-negative_taxidlist filename] [-no_taxid_expansion]
    [-entrez_query entrez_query] [-db_soft_mask filtering_algorithm]
    [-db_hard_mask filtering_algorithm] [-subject subject_input_file]
    [-subject_loc range] [-query input_file] [-out output_file]
    [-evalue evalue] [-word_size int_value] [-gapopen open_penalty]
    [-gapextend extend_penalty] [-perc_identity float_value]
    [-qcov_hsp_perc float_value] [-max_hsps int_value]
    [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value] [-penalty penalty]
    [-reward reward] [-no_greedy] [-min_raw_gapped_score int_value]
    [-template_type type] [-template_length int_value] [-dust DUST_options]
    [-filtering_db filtering_database]
    [-window_masker_taxid window_masker_taxid]
    [-window_masker_db window_masker_db] [-soft_masking soft_masking]
    [-ungapped] [-culling_limit int_value] [-best_hit_overhang float_value]
    [-best_hit_score_edge float_value] [-subject_besthit]
    [-window_size int_value] [-off_diagonal_range int_value]
    [-use_index boolean] [-index_name string] [-lcase_masking]
    [-query_loc range] [-strand strand] [-parse_deflines] [-outfmt format]
    [-show_gis] [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-sorthits sort_hits]
    [-sorthsps sort_hsps] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-mt_mode int_value] [-remote] [-version]
```

::: {.callout-important collapse="true"}

# Argumentos que acepta blast

DESCRIPTION:   Nucleotide-Nucleotide BLAST 2.17.0+

*** Input query options

- **-query <File_In>**: Input file name Default = `-'
 -query_loc <String>
   Location on the query sequence in 1-based offsets (Format: start-stop)
 -strand <String, `both', `minus', `plus'>
   Query strand(s) to search against database/subject
   Default = `both'

 *** General search options
 -task <String, Permissible values: 'blastn' 'blastn-short' 'dc-megablast'
                'megablast' 'rmblastn' >
   Task to execute
   Default = `megablast'
 -db <String>
   BLAST database name
    * Incompatible with:  subject, subject_loc
 -out <File_Out, file name length < 256>
   Output file name
   Default = `-'
 -evalue <Real>
   Expectation value (E) threshold for saving hits. Default = 10 (1000 for
   blastn-short)
 -word_size <Integer, >=4>
   Word size for wordfinder algorithm (length of best perfect match)
 -gapopen <Integer>
   Cost to open a gap
 -gapextend <Integer>
   Cost to extend a gap
 -penalty <Integer, <=0>
   Penalty for a nucleotide mismatch
 -reward <Integer, >=0>
   Reward for a nucleotide match
 -use_index <Boolean>
   Use MegaBLAST database index
   Default = `false'
 -index_name <String>
   MegaBLAST database index name (deprecated; use only for old style indices)

 *** BLAST-2-Sequences options
 -subject <File_In>
   Subject sequence(s) to search
    * Incompatible with:  no_taxid_expansion, db, gilist, seqidlist,
   negative_gilist, negative_seqidlist, taxids, taxidlist, negative_taxids,
   negative_taxidlist, no_taxid_expansion, db_soft_mask, db_hard_mask
 -subject_loc <String>
   Location on the subject sequence in 1-based offsets (Format: start-stop)
    * Incompatible with:  no_taxid_expansion, db, gilist, seqidlist,
   negative_gilist, negative_seqidlist, taxids, taxidlist, negative_taxids,
   negative_taxidlist, no_taxid_expansion, db_soft_mask, db_hard_mask, remote

 *** Formatting options
 -outfmt <String>
   alignment view options:
     0 = Pairwise,
     1 = Query-anchored showing identities,
     2 = Query-anchored no identities,
     3 = Flat query-anchored showing identities,
     4 = Flat query-anchored no identities,
     5 = BLAST XML,
     6 = Tabular,
     7 = Tabular with comment lines,
     8 = Seqalign (Text ASN.1),
     9 = Seqalign (Binary ASN.1),
    10 = Comma-separated values,
    11 = BLAST archive (ASN.1),
    12 = Seqalign (JSON),
    13 = Multiple-file BLAST JSON,
    14 = Multiple-file BLAST XML2,
    15 = Single-file BLAST JSON,
    16 = Single-file BLAST XML2,
    17 = Sequence Alignment/Map (SAM),
    18 = Organism Report,
    20 = Comma-separated values with header lines
   
   Options 6, 7, 10, 17 and 20 can be additionally configured to produce
   a custom format specified by space delimited format specifiers,
   or in the case of options 6, 7, and 10, by a token specified
   by the delim keyword. E.g.: "17 delim=@ qacc sacc score".
   The delim keyword must appear after the numeric output format
   specification.
   The supported format specifiers for options 6, 7 and 10 are:
            qseqid means Query Seq-id
               qgi means Query GI
              qacc means Query accession
           qaccver means Query accession.version
              qlen means Query sequence length
            sseqid means Subject Seq-id
         sallseqid means All subject Seq-id(s), separated by a ';'
               sgi means Subject GI
            sallgi means All subject GIs
              sacc means Subject accession
           saccver means Subject accession.version
           sallacc means All subject accessions
              slen means Subject sequence length
            qstart means Start of alignment in query
              qend means End of alignment in query
            sstart means Start of alignment in subject
              send means End of alignment in subject
              qseq means Aligned part of query sequence
              sseq means Aligned part of subject sequence
            evalue means Expect value
          bitscore means Bit score
             score means Raw score
            length means Alignment length
            pident means Percentage of identical matches
            nident means Number of identical matches
          mismatch means Number of mismatches
          positive means Number of positive-scoring matches
           gapopen means Number of gap openings
              gaps means Total number of gaps
              ppos means Percentage of positive-scoring matches
            frames means Query and subject frames separated by a '/'
            qframe means Query frame
            sframe means Subject frame
              btop means Blast traceback operations (BTOP)
            staxid means Subject Taxonomy ID
          ssciname means Subject Scientific Name
          scomname means Subject Common Name
        sblastname means Subject Blast Name
         sskingdom means Subject Super Kingdom
           staxids means unique Subject Taxonomy ID(s), separated by a ';'
                         (in numerical order)
         sscinames means unique Subject Scientific Name(s), separated by a ';'
         scomnames means unique Subject Common Name(s), separated by a ';'
        sblastnames means unique Subject Blast Name(s), separated by a ';'
                         (in alphabetical order)
        sskingdoms means unique Subject Super Kingdom(s), separated by a ';'
                         (in alphabetical order) 
            stitle means Subject Title
        salltitles means All Subject Title(s), separated by a '<>'
           sstrand means Subject Strand
             qcovs means Query Coverage Per Subject
           qcovhsp means Query Coverage Per HSP
            qcovus means Query Coverage Per Unique Subject (blastn only)
   When not provided, the default value is:
   'qaccver saccver pident length mismatch gapopen qstart qend sstart send
   evalue bitscore', which is equivalent to the keyword 'std'
   The supported format specifier for option 17 is:
                SQ means Include Sequence Data
                SR means Subject as Reference Seq
   Default = `0'
 -show_gis
   Show NCBI GIs in deflines?
 -num_descriptions <Integer, >=0>
   Number of database sequences to show one-line descriptions for
   Not applicable for outfmt > 4
   Default = `500'
    * Incompatible with:  max_target_seqs
 -num_alignments <Integer, >=0>
   Number of database sequences to show alignments for
   Default = `250'
    * Incompatible with:  max_target_seqs
 -line_length <Integer, >=1>
   Line length for formatting alignments
   Not applicable for outfmt > 4
   Default = `60'
 -html
   Produce HTML output?
 -sorthits <Integer, (>=0 and =<4)>
   Sorting option for hits:
   alignment view options:
     0 = Sort by evalue,
     1 = Sort by bit score,
     2 = Sort by total score,
     3 = Sort by percent identity,
     4 = Sort by query coverage
   Not applicable for outfmt > 4
 -sorthsps <Integer, (>=0 and =<4)>
   Sorting option for hps:
     0 = Sort by hsp evalue,
     1 = Sort by hsp score,
     2 = Sort by hsp query start,
     3 = Sort by hsp percent identity,
     4 = Sort by hsp subject start
   Not applicable for outfmt != 0

 *** Query filtering options
 -dust <String>
   Filter query sequence with DUST (Format: 'yes', 'level window linker', or
   'no' to disable) Default = '20 64 1' ('no' for blastn-short)
 -filtering_db <String>
   BLAST database containing filtering elements (i.e.: repeats)
 -window_masker_taxid <Integer>
   Enable WindowMasker filtering using a Taxonomic ID
    * Incompatible with:  no_taxid_expansion
 -window_masker_db <String>
   Enable WindowMasker filtering using this repeats database.
    * Incompatible with:  remote
 -soft_masking <Boolean>
   Apply filtering locations as soft masks
   Default = `true'
 -lcase_masking
   Use lower case filtering in query and subject sequence(s)?

 *** Restrict search or results
 -gilist <String>
   Restrict search of database to list of GIs
    * Incompatible with:  no_taxid_expansion, seqidlist, taxids, taxidlist,
   negative_gilist, negative_seqidlist, negative_taxids, negative_taxidlist,
   remote, subject, subject_loc
 -seqidlist <String>
   Restrict search of database to list of SeqIDs
    * Incompatible with:  no_taxid_expansion, gilist, taxids, taxidlist,
   negative_gilist, negative_seqidlist, negative_taxids, negative_taxidlist,
   remote, subject, subject_loc
 -negative_gilist <String>
   Restrict search of database to everything except the specified GIs
    * Incompatible with:  no_taxid_expansion, gilist, seqidlist, taxids,
   taxidlist, negative_seqidlist, negative_taxids, negative_taxidlist, remote,
   subject, subject_loc
 -negative_seqidlist <String>
   Restrict search of database to everything except the specified SeqIDs
    * Incompatible with:  no_taxid_expansion, gilist, seqidlist, taxids,
   taxidlist, negative_gilist, negative_taxids, negative_taxidlist, remote,
   subject, subject_loc
 -taxids <String>
   Restrict search of database to include only the specified taxonomy IDs and
   their descendants (multiple IDs delimited by ',')
    * Incompatible with:  gilist, seqidlist, taxidlist, negative_gilist,
   negative_seqidlist, negative_taxids, negative_taxidlist, remote, subject,
   subject_loc
 -negative_taxids <String>
   Restrict search of database to everything except the specified taxonomy IDs
   and their descendants (multiple IDs delimited by ',')
    * Incompatible with:  gilist, seqidlist, taxids, taxidlist,
   negative_gilist, negative_seqidlist, negative_taxidlist, remote, subject,
   subject_loc
 -taxidlist <String>
   Restrict search of database to include only the specified taxonomy IDs and
   their descendants 
    * Incompatible with:  gilist, seqidlist, taxids, negative_gilist,
   negative_seqidlist, negative_taxids, negative_taxidlist, remote, subject,
   subject_loc
 -negative_taxidlist <String>
   Restrict search of database to everything except the specified taxonomy IDs
   and their descendants 
    * Incompatible with:  gilist, seqidlist, taxids, taxidlist,
   negative_gilist, negative_seqidlist, negative_taxids, remote, subject,
   subject_loc
 -no_taxid_expansion
   Do not expand the taxonomy IDs provided to their descendant taxonomy IDs 
    * Incompatible with:  subject, subject_loc, window_masker_taxid, gilist,
   seqidlist, negative_gilist, negative_seqidlist, subject, subject_loc
 -entrez_query <String>
   Restrict search with the given Entrez query
    * Requires:  remote
 -db_soft_mask <String>
   Filtering algorithm ID to apply to the BLAST database as soft masking
    * Incompatible with:  db_hard_mask, subject, subject_loc
 -db_hard_mask <String>
   Filtering algorithm ID to apply to the BLAST database as hard masking
    * Incompatible with:  db_soft_mask, subject, subject_loc
 -perc_identity <Real, 0..100>
   Percent identity
 -qcov_hsp_perc <Real, 0..100>
   Percent query coverage per hsp
 -max_hsps <Integer, >=1>
   Set maximum number of HSPs per subject sequence to save for each query
 -culling_limit <Integer, >=0>
   If the query range of a hit is enveloped by that of at least this many
   higher-scoring hits, delete the hit
    * Incompatible with:  best_hit_overhang, best_hit_score_edge
 -best_hit_overhang <Real, (>0 and <0.5)>
   Best Hit algorithm overhang value (recommended value: 0.1)
    * Incompatible with:  culling_limit
 -best_hit_score_edge <Real, (>0 and <0.5)>
   Best Hit algorithm score edge value (recommended value: 0.1)
    * Incompatible with:  culling_limit
 -subject_besthit
   Return only the best HSP for each non overlapping query region
 -max_target_seqs <Integer, >=1>
   Maximum number of aligned sequences to keep 
   (value of 5 or more is recommended)
   Default = `500'
    * Incompatible with:  num_descriptions, num_alignments

 *** Discontiguous MegaBLAST options
 -template_type <String, `coding', `coding_and_optimal', `optimal'>
   Discontiguous MegaBLAST template type
    * Requires:  template_length
 -template_length <Integer, Permissible values: '16' '18' '21' >
   Discontiguous MegaBLAST template length
    * Requires:  template_type

 *** Statistical options
 -dbsize <Int8>
   Effective length of the database 
 -searchsp <Int8, >=0>
   Effective length of the search space

 *** Search strategy options
 -import_search_strategy <File_In>
   Search strategy to use
    * Incompatible with:  export_search_strategy
 -export_search_strategy <File_Out>
   File name to record the search strategy used
    * Incompatible with:  import_search_strategy

 *** Extension options
 -xdrop_ungap <Real>
   X-dropoff value (in bits) for ungapped extensions
 -xdrop_gap <Real>
   X-dropoff value (in bits) for preliminary gapped extensions
 -xdrop_gap_final <Real>
   X-dropoff value (in bits) for final gapped alignment
 -no_greedy
   Use non-greedy dynamic programming extension
 -min_raw_gapped_score <Integer>
   Minimum raw gapped score to keep an alignment in the preliminary gapped and
   traceback stages
 -ungapped
   Perform ungapped alignment only?
 -window_size <Integer, >=0>
   Multiple hits window size, use 0 to specify 1-hit algorithm
 -off_diagonal_range <Integer, >=0>
   Number of off-diagonals to search for the 2nd hit, use 0 to turn off
   Default = `0'

 *** Miscellaneous options
 -parse_deflines
   Should the query and subject defline(s) be parsed?
 -num_threads <Integer, >=1>
   Number of threads (CPUs) to use in the BLAST search
   Default = `1'
    * Incompatible with:  remote
 -mt_mode <Integer, (>=0 and =<2)>
   Multi-thread mode to use in BLAST search:
    0 auto split by database or queries 
    1 split by queries
    2 split by database
   Default = `0'
    * Requires:  num_threads
 -remote
   Execute search remotely?
    * Incompatible with:  gilist, seqidlist, taxids, taxidlist,
   negative_gilist, negative_seqidlist, negative_taxids, negative_taxidlist,
   subject_loc, window_masker_db, num_threads
:::

Aun así, PROBLEMA -> creo que blast para secuencias tan peuqeñas como son los Pc no es útli.
Por ello voy a intentar hacerlo con expresiones regulares, ya que ya me sé las secuencias bien de los promotores:


He añadido el retso de Pc para completar la bbdd, pero en ralidad ahora en lugar de bbdd lo hacemos con RE