---
title: "Semana del 07 al 11 de Septiembre"
number-sections: false
---

# Lunes 07/09

Lectura inicial:

- [Néron, B., Littner, E., Haudiquet, M., Perrin, A., Cury, J., & Rocha, E. P. C. (2022). IntegronFinder 2.0: Identification and Analysis of Integrons across Bacteria, with a Focus on Antibiotic Resistance in Klebsiella. Microorganisms, 10(4), 700.](https://doi.org/10.3390/microorganisms10040700)
- [Moura, A., Jové, T., Ploy, M. C., Henriques, I., & Correia, A. (2012). Diversity of gene cassette promoters in class 1 integrons from wastewater environments. Applied and environmental microbiology, 78(15), 5413–5416.](https://doi.org/10.1128/AEM.00042-12)
- [Vinué, L., Jové, T., Torres, C., & Ploy, M. C. (2011). Diversity of class 1 integron gene cassette Pc promoter variants in clinical Escherichia coli strains and description of a new P2 promoter variant. International journal of antimicrobial agents, 38(6), 526–529.](https://doi.org/10.1016/j.ijantimicag.2011.07.007)

# Martes 08/09

### Organización inicial 
Creación del [repositorio de github](https://github.com/martaaransay/PracticasExternas)

Generación de un entorno de prueba: he hecho un environment_pruebas.yml para poder generar un entorno conda de pruebas.
Comandos para actualizar el entorno (general)

```bash
# El archivo con el environment se llama así:
conda env create -f environment_pruebas.yml
# Activación del entorno creado (se pone en el nombre lo del name de la cabecera del archivo yml)
conda activate pruebas
# Para actualizar el entorno si se han cambiado los paquetes:
conda env update -f environment_pruebas.yml --prune
# --prune elimina del entorno los paquetes que hayas quitado del yml, sino no borra 

``` 

- [**FIXME**]{style="color: red;"} He tenido que pasar de Windows a WSL para la instalación de Integron_Finder (https://github.com/gem-pasteur/Integron_Finder)

### Primeras pruebas con Integron_Finder

Primero descargamos algunos genomas (los que sea) ej. Klebsiella, para ello metemos en el yml para descargar vía NCBI
(  - conda-forge::ncbi-datasets-cli)

Para descargar genomas:

```bash
###para limitar aun más el numeor de genomas que descarga, pongo solo los q se hayan subido a partir del lunes
datasets download genome taxon "Klebsiella pneumoniae" \
--dehydrated  \
--assembly-level complete \
--assembly-source RefSeq \
--released-after "08/09/2026" \
--filename Klebsiella_complete.zip

# --dehydrated -> Cuando las descargas directas en formato .zip dan errores, NCBI recomienda descargar primero solo metadatos y luego rellenarlo (con rehydrate)


# Descomprimimos el archivo
unzip Klebsiella_complete.zip -d Klebsiella

# Y ahora usamos el rehydrate:
datasets rehydrate --directory Klebsiella

# Se guardan los .fna en /Klebsiella/ncbi_dataset/data/<accession>/*.fna

## HE HECHO LO DE MÁS ABAJO!!!!!!
#Para ejecutar IntegronFinder:
integron_finder --outdir results/prueba1_Klebsiella \
Klebsiella/ncbi_dataset/data/*/*.fna

# TENER EN CUENTA FLAGS QUE NO HE USADO AL SER UNA PRUEBA:
# --local-max -> busqueda más sensitive (local detection, slower)
# --func-annot -> anota funcionalmente las cassettes

## PARA que tarde menos y al ser una prueba, hago un bucle con los primeros 5 genomas:
counter=0
for f in data/Klebsiella/ncbi_dataset/data/*/*.fna; do
  if [ "$counter" -eq 5 ]; then
    break
  fi
  integron_finder --promoter-attI --outdir results/prueba1_Klebsiella "$f"
  ((counter=counter+1))
done
```

OUTPUT DE IntegronFinder:
- **mysequences.integrons** : A file with all integrons and their elements detected in all sequences in the input file.
Ese es el archivo que interesa, de ahí hay que buscar la fila que tenga en element -> Pc_int1 que es el promotor

#### Pasar del integronfinder -> sequencia que se corresponde con el promotor

Usando la herramienta seqkit (añadida al .yml:   - bioconda::seqkit), descargamos esa zona del genoma:

```bash
# EJEMPLO DE ESA LINEA en el output de IntegronFinder
# integron_01	NZ_PV022879.1	Pc_int1	29735	29761	-1	NA	Promoter	Pc_1	NA	complete	Yes	NA	lin
## para dar alog más de margen se extraen -10 y +10 nt extra ####FIXME ->????
fasta=data/Klebsiella/ncbi_dataset/data/GCF_059958715.2/GCF_059958715.2_ASM5995871v2_genomic.fna
seqkit subseq --chr NZ_PV022879.1 -r 29725:29771 \
  $fasta \
  | seqkit seq -r -p  > pc_region.fasta

```
[**FIXME:**]{style="color: red;"}

aquí debería hacer un blast??????? o comparrlo con las secuenicas teóricas de promotores y así decidir qué promotor es

## Clasificación de promotores
Información obtenida de:
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1000793

- **PcS:**

Acc Number or reference: U12441 -> 24.3% occurence

TTGACA 17 TAAACT

- **PcW:**

Acc Number or reference: U49101 -> 41.7% occurence

TGGACA 17 TAAGCT

- **PcH1:**

Acc Number or reference: M95287  -> 28% occurence

TGGACA 17 TAAACT

- **PcH2:**

Acc Number or reference: M95U13880  -> 4.4% occurence

TTGACA 17 TAAGCT

- **P2:**

Acc Number or reference: U42226  -> 8.7% occurence

TTGTTA 17 TACAGT

## Integrall

He calculado la abundancia relativa de la primera sheet de la base de datos de Integrall:
(PracticasExternas/data/Integrall/Integrons-Analysis-TJ-V23/Integrons-Analysis-TJ-V23.xlsx)

PERO, he cambiado en la base de datos de Integrall (el .xlsx) un deletede por deleted (por eso el v2 en: 
PracticasExternas/data/Integrall/Integrons-Analysis-TJ-V23/Integrons-Analysis-TJ-V23_v2.xlsx )

Realizado en el script -> ./scripts/T1_abundancia_Integrall.py

# Miércoles 09/09

## Tarea 1 -> Exploración de la base de datos de Integrall

OBJETIVOS:

- T1.1 Extraer y filtrar las entradas correspondientes a integrones de clase 1. Clasificar por especies con especial interés en las cinco especies ESKAPEE

- T1.2 Calcular la abundancia relativa de Pc 4 

He añadido gráfico de la tabla de conteo general, no solo de ESKAPEE.
Además, he hecho la función generalizable por si se necesita usar más adelante
Añadido al script (./scripts/T1_abundancia_Integrall.py)

## Tarea 2 -> Descarga automatizada de genomas desde NCBI 

OBJETIVOS:

- T2.1 Definir los criterios de filtrado de genomas

- T2.2 Desarrollar un script de descarga reproducible y automatizada con NCBI Datasets, adaptado a los criterios definidos

[Guía para usar datasets](https://github.com/ncbi/datasets)

::: {.callout-note collapse="true"}
### FLAGS QUE PUEDE TENER EL COMANDO DE datasets:

--annotated                 Limit to annotated genomes

--assembly-level string     Limit to genomes at one or more assembly levels (comma-separated):
                              * chromosome
                              * complete
                              * contig
                              * scaffold
                                (default "[]")

--assembly-source string    Limit to 'RefSeq' (GCF_) or 'GenBank' (GCA_) genomes (default "all")

--assembly-version string   Optionally return "all" assembly accession versions
                              * all: current assembly versions + all previous versions
                              * current: current assembly versions, plus previous versions only if paired with a current version (default)
                            
--chromosomes strings       Limit to a specified, comma-delimited list of chromosomes, or 'all' for all chromosomes

--dehydrated                Download a dehydrated zip archive including the data report and locations of data files (use the rehydrate command to retrieve data files).

--exclude-atypical          Exclude atypical assemblies

--exclude-multi-isolate     Exclude assemblies from multi-isolate projects
--fast-zip-validation       Skip zip checksum validation after download

--from-type                 Only return records with type material

--include string(,string)   Specify the data files to include (comma-separated).
                              * genome:     genomic sequence
                              * rna:        transcript
                              * protein:    amino acid sequences
                              * cds:        nucleotide coding sequences
                              * gff3:       general feature file
                              * gtf:        gene transfer format
                              * gbff:       GenBank flat file
                              * seq-report: sequence report file
                              * all:        include all available file types (equivalent to genome,protein,cds,gff3,gtf,gbff,rna,seq-report)
                              * none:       do not retrieve any sequence files
                                (default [genome])

--mag string                Limit to metagenome assembled genomes (only) or remove them from the results (exclude) (default "all")

--preview                   Show information about the requested data package

--reference                 Limit to reference genomes

--released-after string     Limit to genomes released on or after a specified date (free format, ISO 8601 YYYY-MM-DD recommended)

--released-before string    Limit to genomes released on or before a specified date (free format, ISO 8601 YYYY-MM-DD recommended)

--search strings            Limit results to genomes with specified text in the searchable fields:
                            species and infraspecies, assembly name and submitter.
                            To search multiple strings, use the flag multiple times.
:::

He generado el código (scripts/T2_descarga_genomas.py) pero se peuden añadir más métricas que sean por umbrales numéricos:
-  para ello habría que ejecutar *datasets summary genome ...* con la flag *--as-json-lines*. En ese JSON se puede filtrar numéricamente y los válidos pasarlos al script creado


He añadido la parte de las métricas, pero fatla definir los umbrales correctamente ([**FIXME**]{style="color: red;"})
- falta además limpiar un poco el código y comentarlo
- hacer alguna prueba de errores también

# Jueves 10/09

OBJETIVOS INCIAL HOY:

Acabar bien T2 (descarga automatizda de genomas) -> limpiar código, comprobar errores de cada función individual y a nivel general
Mirar si es necesario el [integron-filtering](https://github.com/timghaly/integron-filtering) de forma previa a ejecutar IntegronFinder2
Empezar códigdo de integron-filtering + IntegronFinder2

## Tarea 2 -> Descarga automatizada de genomas desde NCBI 

Script en teoría terminado (scripts/T2_descarga_genomas.py), y probado errores (scripts/T2_tests.py).
Uso del script al final del mismo (scripts/T2_descarga_genomas.py)

## Tarea 3 --> Detección de integrones de clase 1 y clasificación en función de su región promotora Pc

Primero voy a probar lo que tarda en ejecutarse IntrogronFinder2 sobre el conjunto de genomas que he guardado (aprox 2k-3k) y luego miro lo de integron-filtering