# Import libraries 
import os
import subprocess
import time
import shlex
import re
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor
# Import functions from other scripts
from pipeline_inicial.useful_funct import list_fasta_files
from plotting import plot_evalue, plot_bitscore, plot_evalue_thresholds, plot_hits_comparison, plot_hits_overlap
from pipeline_inicial.T3_2_integronfinder import Integron_Finder
from pipeline_inicial.T3_1_integronfiltering import integron_filtering
from general import contig_to_genome

# --------Definition of functions
#------------------------ Function to run blastn
def run_blastn(query, output, db, max_target, evalue_threshold = 10):
    """
    Executes the blastn command with the specified query, output file, and database.

    Args
    ------
    query (str): The path to the query fasta file.
    output (str): The path to the output file where results will be saved.
    db (str): The path to the blast database.
    max_target (int): Maximum number of aligned sequences keeped into the results.
    evalue_threshold (int): E-value threshold.
                            Default to 10.

    Return
    ------
    output (str): The path to the output file where results are saved.
    elapsed (float): The time taken to execute the blastn command in seconds.
    """
    # Creates the output directory to avoid errors
    os.makedirs(os.path.dirname(output), exist_ok=True)
    # Blastn command
    blast_cmd = ["blastn", "-query", query, # Query fasta file
                 "-db", db, # Blast database
                 "-out", output, 
                 "-max_target_seqs", str(max_target), # Max number of aligned seqs to keep
                 "-evalue", str(evalue_threshold),
                 "-outfmt", "6"] # Output format 6 (tabular)
    start = time.time() # Start time to measure execution time
    # Execute the command and handle errors
    print(f"Executing: \n{shlex.join(blast_cmd)}")
    try:
        subprocess.run(blast_cmd, 
                       check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"Error executing blastn:\n{e.stderr}")
        return

    total_time = time.time() - start # End time to measure execution time

    return output, total_time

#------------------------ Function to process tsv files of blastn results
def process_tsv(tsv_files):
    """
    Process the tsv files generated by blastn and returns the dataframes obtained,
    log10 of e-values, bitscores, and labels.
    
    Args
    ------
    tsv_files (dict): A dictionary where keys are the names of the queries and 
                      values are the paths to the corresponding tsv files.

    Return
    ------
    dfs (dict): A dictionary where keys are the names of the queries and
                values are the corresponding pandas dataframes.
    log_data (list): A list of lists containing the -log10 of e-values for each query.
    bitscore_data (list): A list of lists containing the bitscores for each query.
    labels (list): A list of the names of the queries.
    """
    
    # Columns of the tsv files
    columns = ["query_id", "seq_id", "identity", "length", 
               "mismatch", "gapopen", "query_start", "query_end", 
               "seq_start", "seq_end", "Evalue", "BitScore"]
    # Lists and dictionaries to store data
    log_data = []
    bitscore_data = []
    labels = []
    dfs = {}

    for query, path in tsv_files.items(): # For each query and its tsv file
        # Reads the tsv file and converts it into a df
        df = pd.read_csv(path, sep="\t", names=columns) 
        dfs[query] = df # Stores the df in the dictionary of dfs
        evalues = df["Evalue"] # E-values of the query
        # To avoid errors with the log10(0)
        nonzero = evalues[evalues>0] # Stores the non-zero e-values
        if nonzero.empty: min_value = 1e-300 # If all are 0, 1e-300 is used
        else: min_value = nonzero.min()/10 # The minimum value (non-zero) / 10 is used
        evalues = df["Evalue"].replace(0, min_value) # Replace the 0 values
        # Append the values to the corresponding lists
        log_data.append(-np.log10(evalues)) # Calculate log10 of evalues 
        bitscore_data.append(df["BitScore"]) # Append the bitscores to the list
        labels.append(query) # Append the query name to the labels list

    return dfs, log_data, bitscore_data, labels

def genome_key(name):
    """Normaliza a la accession GCF_/GCA_ (ej. GCF_000809905.3)."""
    m = re.search(r"GC[FA]_\d+\.\d+", str(name))
    return m.group(0) if m else str(name)



def run_method(i, list_files, num_genomes_each, cpu):
    """i=0 -> IF2 ; i=1 -> Integron-filtering + IF2"""
    base = f"results/{num_genomes_each}genomes"
    dir_IF2 = f"{base}/IF2" if i == 0 else f"{base}/IntFilt+IF2/IF2"
    os.makedirs(dir_IF2, exist_ok=True)

    start = time.time()
    hits, failed = {}, []

    for each_file in list_files:
        original_acc = os.path.splitext(os.path.basename(each_file))[0]

        if i == 1:
            dir_IntFilt = f"{base}/IntFilt+IF2/IntFilt/{original_acc}"
            os.makedirs(dir_IntFilt, exist_ok=True)
            file = integron_filtering(genome_path=each_file, outdir=dir_IntFilt)
            if not file:                      # sin integrón -> no IF2
                hits[original_acc] = 0
                continue
            each_file = file

        acc_for_IF2 = os.path.splitext(os.path.basename(each_file))[0]
        gbk_files = Integron_Finder(genome_path=each_file,
                                    genome_acc=acc_for_IF2,
                                    outdir=dir_IF2,
                                    cpu=cpu)
        if gbk_files is None:
            print(f"[método {i}] IF2 falló en {original_acc}")
            failed.append(original_acc)
            continue
        hits[original_acc] = len(gbk_files)

    unique_genomes = [g for g, n in hits.items() if n > 0]
    return {"hits": hits,
            "failed": failed,
            "general_hits": sum(hits.values()),
            "unique_genomes": unique_genomes,
            "unique_hits": len(unique_genomes),
            "time": time.time() - start}

# --------Main code
if __name__ == "__main__":
    ############################## 1) BLASTn:

    # List of queries to analyze
    fasta_files = ["data/Int1/Int1.fa", 
                   "data/Int1/Int1_Pc_pattern.fa", 
                   "data/Int1/Int1_no_Pc.fa"]
    # Dictionaries to store results and times of execution
    all_results = {}
    all_times = {}
    
    num_genomes_each = 500 # Number of genomes of each specie in the database
    
    for each_query in fasta_files: # For each query
        name = os.path.basename(each_query)

        each_result, each_time = run_blastn(query = each_query, 
                                            output = f"results/{str(num_genomes_each)}genomes/blast/blast_{name}.tsv",
                                            db = f"../data/{str(num_genomes_each)}genomes/db/db",
                                            max_target = num_genomes_each * 5 * 5) # max num of seqs to keep: size of db * 5
        # Store results and times of each query
        all_results[each_query] = each_result
        all_times[each_query] = each_time

    dfs, evalues, bitscore, labels = process_tsv(all_results) # Process tsv files

    genomes_dir = f"../data/{num_genomes_each}genomes"
    mapping = contig_to_genome(genomes_dir)  

    # Plotting blastn results
    outdir = f"results/plots/{str(num_genomes_each)}genomes"
    general_title = f"- db: {str(num_genomes_each)} genomes * 5 species ({str(num_genomes_each*5)})"

    plot_evalue(evalues, labels, title = f"E-Values distribution {general_title}", outdir = outdir)
    plot_bitscore(bitscore, labels, title = f"BitScore distribution {general_title}", outdir = outdir)
    plot_evalue_thresholds(dfs, all_times, title = f"E-Values thresholds {general_title}", outdir = outdir)

    # Store the blastn result of a unique query to compare with other methods:
    chosen_query = "data/Int1/Int1_Pc_pattern.fa"
    blast_df = dfs[chosen_query]
    blast_general_hits = len(blast_df)


    contigs = blast_df["seq_id"].unique()
    print("Contigs sin mapear:", sum(c not in mapping for c in contigs))

    set_blast = {genome_key(mapping[c]) for c in contigs if c in mapping}
    blast_unique_hits = len(set_blast)          # genomas, no contigs
    t_blast = all_times[chosen_query]           # solo la query comparada

    ############################## 2) IntegronFinder2 and 3) Integron-filtering + IntegronFinder2
     

    list_files = list_fasta_files(genomes_dir, depth=5)
    cpu_each = max(1, os.cpu_count() // 2)     # reparte los núcleos entre los 2 métodos

    with ThreadPoolExecutor(max_workers=2) as ex:
        fut_IF2 = ex.submit(run_method, 0, list_files, num_genomes_each, cpu_each)
        fut_Int = ex.submit(run_method, 1, list_files, num_genomes_each, cpu_each)
        res_IF2 = fut_IF2.result()
        res_Int = fut_Int.result()


    print("Fallos IF2:", res_IF2["failed"], "| Fallos IntFilt+IF2:", res_Int["failed"])

    hits_summary = {"BLAST": (blast_general_hits, blast_unique_hits),
                    "IntegronFinder2": (res_IF2["general_hits"], res_IF2["unique_hits"]),
                    "Integron-filtering+IF2": (res_Int["general_hits"], res_Int["unique_hits"])}
    times = {"BLAST": t_blast,
             "IntegronFinder2": res_IF2["time"],
             "Integron-filtering+IF2": res_Int["time"]}

    set_IF2 = {genome_key(g) for g in res_IF2["unique_genomes"]}
    set_IntFiltIF2 = {genome_key(g) for g in res_Int["unique_genomes"]}
    print(list(set_blast)[:3], list(set_IF2)[:3])

    plot_hits_comparison(hits_summary, times,
                         title=f"Method comparison {general_title}", outdir=outdir)

    sets_dict = {"BLAST": set_blast,
                 "IntegronFinder2": set_IF2,
                 "Integron-filtering+IF2": set_IntFiltIF2}
    plot_hits_overlap(sets_dict, title=f"Method comparison {general_title}", outdir=outdir)