# Import libraries 
import os
import subprocess
import time
import shlex
import glob
import pandas as pd
import numpy as np
# Import functions from other scripts
from pipeline_inicial.useful_funct import list_fasta_files
from plotting import plot_evalue, plot_bitscore, plot_evalue_thresholds#, plot_hits_comparison, plot_hits_overlap
from pipeline_inicial.T3_2_integronfinder import Integron_Finder
from pipeline_inicial.T3_1_integronfiltering import integron_filtering

# --------Definition of functions
#------------------------ Function to run blastn
def run_blastn(query, output, db, max_target, evalue_threshold = 10):
    """
    Executes the blastn command with the specified query, output file, and database.

    Args
    ------
    query (str): The path to the query fasta file.
    output (str): The path to the output file where results will be saved.
    db (str): The path to the blast database.
    max_target (int): Maximum number of aligned sequences keeped into the results.
    evalue_threshold (int): E-value threshold.
                            Default to 10.

    Return
    ------
    output (str): The path to the output file where results are saved.
    elapsed (float): The time taken to execute the blastn command in seconds.
    """
    # Creates the output directory to avoid errors
    os.makedirs(os.path.dirname(output), exist_ok=True)
    # Blastn command
    blast_cmd = ["blastn", "-query", query, # Query fasta file
                 "-db", db, # Blast database
                 "-out", output, 
                 "-max_target_seqs", str(max_target), # Max number of aligned seqs to keep
                 "-evalue", str(evalue_threshold),
                 "-outfmt", "6"] # Output format 6 (tabular)
    start = time.time() # Start time to measure execution time
    # Execute the command and handle errors
    print(f"Executing: \n{shlex.join(blast_cmd)}")
    try:
        subprocess.run(blast_cmd, 
                       check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"Error executing blastn:\n{e.stderr}")
        return

    total_time = time.time() - start # End time to measure execution time

    return output, total_time

#------------------------ Function to process tsv files of blastn results
def process_tsv(tsv_files):
    """
    Process the tsv files generated by blastn and returns the dataframes obtained,
    log10 of e-values, bitscores, and labels.
    
    Args
    ------
    tsv_files (dict): A dictionary where keys are the names of the queries and 
                      values are the paths to the corresponding tsv files.

    Return
    ------
    dfs (dict): A dictionary where keys are the names of the queries and
                values are the corresponding pandas dataframes.
    log_data (list): A list of lists containing the -log10 of e-values for each query.
    bitscore_data (list): A list of lists containing the bitscores for each query.
    labels (list): A list of the names of the queries.
    """
    
    # Columns of the tsv files
    columns = ["query_id", "seq_id", "identity", "length", 
               "mismatch", "gapopen", "query_start", "query_end", 
               "seq_start", "seq_end", "Evalue", "BitScore"]
    # Lists and dictionaries to store data
    log_data = []
    bitscore_data = []
    labels = []
    dfs = {}

    for query, path in tsv_files.items(): # For each query and its tsv file
        # Reads the tsv file and converts it into a df
        df = pd.read_csv(path, sep="\t", names=columns) 
        dfs[query] = df # Stores the df in the dictionary of dfs
        evalues = df["Evalue"] # E-values of the query
        # To avoid errors with the log10(0)
        nonzero = evalues[evalues>0] # Stores the non-zero e-values
        if nonzero.empty: min_value = 1e-300 # If all are 0, 1e-300 is used
        else: min_value = nonzero.min()/10 # The minimum value (non-zero) / 10 is used
        evalues = df["Evalue"].replace(0, min_value) # Replace the 0 values
        # Append the values to the corresponding lists
        log_data.append(-np.log10(evalues)) # Calculate log10 of evalues 
        bitscore_data.append(df["BitScore"]) # Append the bitscores to the list
        labels.append(query) # Append the query name to the labels list

    return dfs, log_data, bitscore_data, labels

# --------Main code
if __name__ == "__main__":
    ############################## 1) BLASTn:

    # List of queries to analyze
    fasta_files = ["data/Int1/Int1.fa", 
                   "data/Int1/Int1_Pc_pattern.fa", 
                   "data/Int1/Int1_no_Pc.fa"]
    # Dictionaries to store results and times of execution
    all_results = {}
    all_times = {}
    
    num_genomes_each = 10 # Number of genomes of each specie in the database
    
    for each_query in fasta_files: # For each query
        name = os.path.basename(each_query)

        each_result, each_time = run_blastn(query = each_query, 
                                            output = f"results/{str(num_genomes_each)}genomes/blast/blast_{name}.tsv",
                                            db = f"data/{str(num_genomes_each)}genomes/db/db",
                                            max_target = num_genomes_each * 5 * 5) # max num of seqs to keep: size of db * 5
        # Store results and times of each query
        all_results[each_query] = each_result
        all_times[each_query] = each_time

    dfs, evalues, bitscore, labels = process_tsv(all_results) # Process tsv files

    # Plotting blastn results
    outdir = f"results/plots/{str(num_genomes_each)}genomes"
    general_title = f"- db: {str(num_genomes_each)} genomes * 5 species ({str(num_genomes_each*5)})"

    plot_evalue(evalues, labels, title = f"E-Values distribution {general_title}", outdir = outdir)
    plot_bitscore(bitscore, labels, title = f"BitScore distribution {general_title}", outdir = outdir)
    plot_evalue_thresholds(dfs, all_times, title = f"E-Values thresholds {general_title}", outdir = outdir)

    # Store the blastn result of a unique query to compare with other methods:
    chosen_query = "data/Int1/Int1.fa"  
    blast_df = dfs[chosen_query]
    blast_general_hits = len(blast_df)
    blast_unique_hits = blast_df["seq_id"].nunique()
    blast_unique_genome = blast_df["seq_id"].unique()
    t_blast = sum(all_times.values()) / len(all_times.values())

    ############################## 2) IntegronFinder2 and 3) Integron-filtering + IntegronFinder2
    analysis = [0, 1] 
    for i in analysis:
        # i=0 -> IntegronFinder2 
        # i=1 -> Integron-filtering + IntegronFinder2
        genomes_dir = f"data/{str(num_genomes_each)}genomes"
        list_files = list_fasta_files(genomes_dir, depth = 5) # List fasta files
        
        start = time.time() # Start time to measure execution time
        
        hits = {} # Dictionary to store results

        for each_file in list_files: 
            original_acc = os.path.splitext(os.path.basename(each_file))[0] # accession of the current genome
            
            if i == 1: # For Integron-Filtering + IF2
                # Directories to store the results of the programs
                os.makedirs(f"results/{str(num_genomes_each)}genomes/IntFilt+IF2", exist_ok=True) # parental dir

                dir_IntFilt = f"results/{str(num_genomes_each)}genomes/IntFilt+IF2/IntFilt/{original_acc}"
                os.makedirs(dir_IntFilt, exist_ok=True)

                dir_IF2 = f"results/{str(num_genomes_each)}genomes/IntFilt+IF2/IF2"
                
                file = integron_filtering(genome_path = each_file,
                                          outdir = dir_IntFilt)
                if file: # If integron-filtering founded an integron, the path is updated to execute IF2
                    each_file = file
                    
                else: # If no integron, no IF2
                    hits[original_acc] = 0 
                    continue
                    
            else: # For IF2 (only)
                dir_IF2 = f"results/{str(num_genomes_each)}genomes/IF2"
            acc_for_IF2 = os.path.splitext(os.path.basename(each_file))[0]
            # Creates the propper dir IF2
            os.makedirs(dir_IF2, exist_ok=True)
            # Executes IF2
            gbk_files = Integron_Finder(genome_path = each_file,
                                        genome_acc = acc_for_IF2,
                                        outdir = dir_IF2)
            # Stores the number of hits (= number of gbk files) per acc
            hits[original_acc] = len(gbk_files)

        # Analyses the results obtained for each method
        general_hits = sum(hits.values()) # Total hits
        unique_genomes = [] # List to store the genomes with >0 hits
        unique_hits = 0
        for id_genome, num_hits, in hits.items():
            if num_hits > 0:
                unique_hits += 1 # Counts only genomes with >0 hits
                unique_genomes.append(id_genome)

        
        total_time = time.time() - start # Execution time

        print(f"Total analyzed = {len(hits)}")
        print(f"Total hits = {general_hits}")
        print(f"Total unique hits = {unique_hits}")
        print(f"Total time = {total_time}")
        
        # Store the results of each method to compare 
        if i == 0: # only IF2
            hits_IF2 = hits
            general_hits_IF2 = general_hits
            unique_hits_IF2 = unique_hits
            unique_genomes_IF2 = unique_genomes
            t_IF2 = total_time

        if i == 1: #Intfilt + IF2
            hits_IntFiltIF2 = hits
            general_hits_IntFiltIF2 = general_hits
            unique_hits_IntFiltIF2 = unique_hits
            unique_genomes_IntFiltIF2 = unique_genomes
            t_IntFiltIF2 = total_time
    
    # Summary of all results
    hits_summary = {"BLAST": (blast_general_hits, blast_unique_hits),
                    "IntegronFinder2": (general_hits_IF2, unique_hits_IF2),
                    "Integron-filtering+IF2": (general_hits_IntFiltIF2, unique_hits_IntFiltIF2),
                    }
    times = {"BLAST": t_blast, 
             "IntegronFinder2": t_IF2, 
             "Integron-filtering+IF2": t_IntFiltIF2}

    # Plotting comparision:
    plot_hits_comparison(hits_summary, times)

    # Create sets to study overlapping with venn diagrams
    set_blast = set(blast_unique_genome)
    set_IF2 = set(unique_genomes_IF2) 
    set_IntFiltIF2 = set(unique_genomes_IntFiltIF2)
    
    # Dictionary of sets
    sets_dict = {"BLAST": set_blast,
                "IntegronFinder2": set_IF2,
                "Integron-filtering+IF2": set_IntFiltIF2
                }
    
    plot_hits_overlap(sets_dict)