# Import libraries 
import os
import time
import re
import pandas as pd
import numpy as np
from concurrent.futures import ThreadPoolExecutor


# Import functions from other scripts
from pipeline.downloadgenomes import datasets_flags, download_genomes
from pipeline.generate_db import download_species_genomes, generate_multifasta, generate_db
from pipeline.blastn import run_blastn
from pipeline.useful_funct import list_fasta_files, contig_to_genome, genome_key, unique_genome_files
from pipeline.parallel_download import process_all
from plot.plotting import plot_evalue, plot_bitscore, plot_evalue_thresholds, plot_hits_comparison, plot_hits_overlap
from pipeline.integronfinder import Integron_Finder
from pipeline.integronfiltering import integron_filtering
from pipeline.analyze_Pc import extract_integron_info_gbk


# --------Definition of functions

#------------------------ Function to process tsv files of blastn results for comparison
def process_tsv2compare(tsv_files):
    """
    Process the tsv files generated by blastn and returns the dataframes obtained,
    log10 of e-values, bitscores, and labels.
    
    Args
    ------
    tsv_files (dict): A dictionary where keys are the names of the queries and 
                      values are the paths to the corresponding tsv files.

    Return
    ------
    dfs (dict): A dictionary where keys are the names of the queries and
                values are the corresponding pandas dataframes.
    log_data (list): A list of lists containing the -log10 of e-values for each query.
    bitscore_data (list): A list of lists containing the bitscores for each query.
    labels (list): A list of the names of the queries.
    """
    
    # Columns of the tsv files
    columns = ["query_id", "seq_id", "identity", "length", 
               "mismatch", "gapopen", "query_start", "query_end", 
               "seq_start", "seq_end", "Evalue", "BitScore"]
    # Lists and dictionaries to store data
    log_data = []
    bitscore_data = []
    labels = []
    dfs = {}

    for query, path in tsv_files.items(): # For each query and its tsv file
        
        try:
            # Reads the tsv file and converts it into a df
            df = pd.read_csv(path, sep = "\t", names = columns)
        except pd.errors.EmptyDataError:
            # Control to avoid errors if the tsv is empty
            df = pd.DataFrame(columns = columns)

        dfs[query] = df # Stores the df in the dictionary of dfs
        evalues = df["Evalue"] # E-values of the query
        # To avoid errors with the log10(0)
        nonzero = evalues[evalues>0] # Stores the non-zero e-values
        if nonzero.empty: min_value = 1e-300 # If all are 0, 1e-300 is used
        else: min_value = nonzero.min()/10 # The minimum value (non-zero) / 10 is used
        evalues = df["Evalue"].replace(0, min_value) # Replace the 0 values
        
        # Append the values to the corresponding lists
        log_data.append(-np.log10(evalues)) # Calculate log10 of evalues 
        bitscore_data.append(df["BitScore"]) # Append the bitscores to the list
        labels.append(query) # Append the query name to the labels list

    return dfs, log_data, bitscore_data, labels


#------------------------ Function to execute IF2 and Integron-filtering + IF2
def run_method(idx_analysis, parent_results_dir, list_files, cpu):
    """
    Run IntegronFinder2 on a list of genomes, either alone or after integron-filtering.

    Args
    ------
    idx_analysis (int): Analysis mode. 
                        - 0 runs IF2 alone
                        - 1 runs integron-filtering followed by IF2.
    parent_results_dir (str): Parent directory where results are stored. 
    list_files (list): Paths to the genome files to analyze. 
    cpu (int): Number of CPUs passed to IF2.

    Return
    ------
    results (dict): Dictionary with the following keys:
                    - "hits" (dict): integrons detected per genome accession.
                    - "failed" (list): accessions for which the IF2 execution failed.
                    - "general_hits" (int): total number of integrons detected.
                    - "unique_genomes" (list): accessions with at least one hit.
                    - "unique_hits" (int): number of genomes with at least one hit.
                    - "time" (float): total execution time in seconds.
    """
    # Create the directory to store IF2 results (executed alone or with integron-filtering)
    if idx_analysis == 0:
        dir_IF2 = f"{parent_results_dir}/IF2" 
    if idx_analysis == 1:
        dir_IF2 = f"{parent_results_dir}/IntFilt+IF2/IF2"
    
    os.makedirs(dir_IF2, exist_ok=True)

    start = time.time() # Start time
    hits, failed = {}, [] # To control errors in the IF2 execution

    for each_file in list_files: # Iterates over the files
        # Accession of the genome
        original_acc = os.path.splitext(os.path.basename(each_file))[0]

        if idx_analysis == 1: # Integron-filtering + IF2
            # Create the directory to store integron-filtering results
            dir_IntFilt = f"{parent_results_dir}/IntFilt+IF2/IntFilt/{original_acc}"
            os.makedirs(dir_IntFilt, exist_ok=True)

            # Executes integron-filtering script
            file = integron_filtering(genome_path = each_file, 
                                      outdir = dir_IntFilt)
            
            if file: # If no integron detected by integron-filtering, adds a 0 into hits dict                      
                each_file = file
            else:
                continue
                
            # If integron detected, updates the path to the genome filtered
            
        # Updates the accession (adds _genomic)
        acc_for_IF2 = os.path.splitext(os.path.basename(each_file))[0]
        # Executes IntegronFinder2
        gbk_files = Integron_Finder(genome_path = each_file,
                                    genome_acc = acc_for_IF2,
                                    outdir = dir_IF2,
                                    cpu = cpu) # cpu are limited to 4 in the defined function
        # If no integron detected by IF2, gbk_files is an empty list

        if gbk_files is None: # If gbk_files is None, an error occured
            failed.append(original_acc)
            continue # Skips the current genome
        # Adds the number of integrons detected by IF2 into hits dict
        info = extract_integron_info_gbk(original_acc, gbk_files)
        n_integrases = 0
        for i in info:
                if not i["calin"]:
                    n_integrases += 1
        hits[original_acc] = n_integrases
                

    unique_genomes = [] # List to store genomes with 1 hit or more
    for accession, num_hits in hits.items():
        if num_hits > 0:
            unique_genomes.append(accession)
    # Adds information into hits dictionary
    results = {"hits": hits,
               "failed": failed,
               "general_hits": sum(hits.values()),
               "unique_genomes": unique_genomes,
               "unique_hits": len(unique_genomes),
               "time": time.time() - start}
    
    return results

# --------Main code
if __name__ == "__main__":
    ### 0) Creating the database with genomes:

    num_genomes_each = 250 # Number of genomes of each specie in the database
    flag_db_created = False
    if not flag_db_created:

        flags = datasets_flags(assembly_level = "complete,chromosome,contig",
                               exclude_atypical = True,
                               mag = False)
        # species to download
        names = {"Ecoli" : "Escherichia coli", 
                "Klebsiella" : "Klebsiella pneumoniae",
                "Pseudomonas" : "Pseudomonas aeruginosa",
                "Acinetobacter" : "Acinetobacter baumannii",
                "Enterobacter" : "Enterobacter"}

        ## For downloading normal genomes --> download_genomes() directly
        
        ## For downloading genomes from a group of species --> download_species_genomes()
        dirs = download_species_genomes(species = names, 
                                        outdir = f"../data/{str(num_genomes_each)}genomes", 
                                        target_num = num_genomes_each, 
                                        flags = flags)
        # Rehydrates all the genomes
        failed = process_all(dirs, 
                             total_workers = 30, 
                             n_split = 500)

        if failed: 
            print(f"Failed to rehydrate: {failed}")
            exit(1)

        # Path to the multifasta file 
        multifasta_path = f"../data/{str(num_genomes_each)}genomes/multifasta_genomes.fasta"

        # Generates multifasta file
        generate_multifasta(path_to_genomes = f"../data/{str(num_genomes_each)}genomes/*/*/ncbi_dataset/data/*/*.fna",
                            outfile = multifasta_path)
        # Generates the database
        generate_db(multifasta = multifasta_path,
                    out_db = f"../data/{str(num_genomes_each)}genomes/db/db")


    ############################## 1) BLASTn:

    # List of queries to analyze
    fasta_files = ["data/Int1/Int1.fa", 
                   "data/Int1/Int1_Pc_pattern.fa", 
                   "data/Int1/Int1_no_Pc.fa"]
    # Dictionaries to store results and times of execution
    all_results = {}
    all_times = {}

    genomes_dir = f"../data/{num_genomes_each}genomes"
    for each_query in fasta_files: # For each query
        name = os.path.basename(each_query)

        # Blastn
        each_result, each_time = run_blastn(query = each_query, 
                                            output = f"results/{str(num_genomes_each)}genomes/blast/blast_{name}.tsv",
                                            db = f"../data/{str(num_genomes_each)}genomes/db/db",
                                            max_target = len(contig_to_genome(genomes_dir))) # max num of seqs to keep: - mapping length
        
        # Store results and times of each query
        all_results[each_query] = each_result
        all_times[each_query] = each_time

    dfs, evalues, bitscore, labels = process_tsv2compare(all_results) # Process tsv files

    # Plotting blastn results
    outdir = f"results/plots/{str(num_genomes_each)}genomes"
    general_title = f"- db: {str(num_genomes_each)} genomes * 5 species ({str(num_genomes_each*5)})"

    plot_evalue(evalues, labels, 
                title = f"E-Values distribution {general_title}", outdir = outdir)
    plot_bitscore(bitscore, labels, 
                  title = f"BitScore distribution {general_title}", outdir = outdir)
    plot_evalue_thresholds(dfs, all_times, 
                           title = f"E-Values thresholds {general_title}", outdir = outdir)

    # Store the blastn result of a unique query to compare with other methods
    chosen_query = "data/Int1/Int1_Pc_pattern.fa"
    blast_df = dfs[chosen_query]
    blast_general_hits = len(blast_df)
    contigs = blast_df["seq_id"].unique()

    # Creates the mapping dictionary (id: path)
    mapping = contig_to_genome(genomes_dir)
    # Set to store blast results  
    set_blast = set()
    for each_contig in contigs: # Iterates over contigs
        if each_contig in mapping: # Checks if the contig is in the mapping dictionary
            # If the contig is correct, stores in the set its genome accession
            acc = genome_key(mapping[each_contig])
            set_blast.add(acc)

    blast_unique_hits = len(set_blast) # Unique genomes
    t_blast = all_times[chosen_query] # Time of the selected query

    ############################## 2) IntegronFinder2 and 3) Integron-filtering + IntegronFinder2

    # List fasta files with 5 levels of depth using the root directory
    all_files = list_fasta_files(genomes_dir, depth = 5)

    unique_files = unique_genome_files(all_files)

    list_files = list(unique_files.values())
    # Divides the cores between methods
    cpu_each = max(1, os.cpu_count() // 2) 

    parent_results_dir = f"results/{str(num_genomes_each)}genomes"


    with ThreadPoolExecutor(max_workers=2) as executor:
        # run_method(idx_analysis, parent_results_dir, list_files, cpu)
        
        # idx_analysis = 0 -> IntegronFinder2
        fut_IF2 = executor.submit(run_method, 
                                  0, parent_results_dir, list_files, cpu_each)
        # idx_analysis = 1 -> integron-filtering + IntegronFinder2
        fut_IntIF2 = executor.submit(run_method, 
                                          1, parent_results_dir, list_files, cpu_each)
        
        res_IF2 = fut_IF2.result()
        res_IntIF2 = fut_IntIF2.result()

        # Store results
        IF2_general_hits = res_IF2["general_hits"]
        IF2_unique_genomes = res_IF2["unique_genomes"]
        t_IF2 = res_IF2["time"]

        IntIF2_general_hits = res_IntIF2["general_hits"]
        IntIF2_unique_genomes = res_IntIF2["unique_genomes"]
        t_IntIF2 = res_IntIF2["time"]


    # Creating sets of IF2 and integron-filtering+IF2 results:
    set_IF2 = set()
    for IF2_genome in IF2_unique_genomes: # Iterates over genomes
        IF2_acc = genome_key(IF2_genome) # Store the accession in the set 
        set_IF2.add(IF2_acc)
    # Unique hits from normalized sets
    IF2_unique_hits = len(set_IF2)

    set_IntIF2 = set()
    for IntIF2_genome in IntIF2_unique_genomes: 
        IntIF2_acc = genome_key(IntIF2_genome) 
        set_IntIF2.add(IntIF2_acc)

    IntIF2_unique_hits = len(set_IntIF2)

    hits_summary = {"BLAST": (blast_general_hits, blast_unique_hits),
                    "IntegronFinder2": (IF2_general_hits, IF2_unique_hits),
                    "Integron-filtering+IF2": (IntIF2_general_hits, IntIF2_unique_hits)}
    
    times = {"BLAST": t_blast,
             "IntegronFinder2": t_IF2,
             "Integron-filtering+IF2": t_IntIF2}
    
    # Plotting methods comparison
    plot_hits_comparison(hits_summary, times,
                         title = f"Method comparison {general_title}", 
                         outdir = outdir)

    # Creates sets dictionary
    sets_dict = {"BLAST": set_blast,
                 "IntegronFinder2": set_IF2,
                 "Integron-filtering+IF2": set_IntIF2}

    # Plotting overlapping genomes
    plot_hits_overlap(sets_dict, 
                      title = f"Method comparison {general_title}", 
                      outdir = outdir)

    #### To store plotted results:

    # BLAST: number of hits per genome
    blast_counts = {}
    for each_contig in blast_df["seq_id"]:
        if each_contig in mapping:
            acc = genome_key(mapping[each_contig])
            blast_counts[acc] = blast_counts.get(acc, 0) + 1

    # IF2 and IntFilt+IF2: number of integrons per genome (normalized accession)
    IF2_counts = {genome_key(k): v for k, v in res_IF2["hits"].items()}
    IntIF2_counts = {genome_key(k): v for k, v in res_IntIF2["hits"].items()}


    # Universe: all the genomes analyzed (including those without hits)
    all_accs = sorted(unique_files.keys())

    df_genomes = pd.DataFrame({
        "genome": all_accs,
        "path": [unique_files[a] for a in all_accs],
        "BLAST_hits": [blast_counts.get(a, 0) for a in all_accs],
        "IF2_hits": [IF2_counts.get(a, 0) for a in all_accs],
        "IntFilt_IF2_hits": [IntIF2_counts.get(a, 0) for a in all_accs],
    })

    # Presence/absence (= unique hits)
    df_genomes["in_BLAST"] = df_genomes["BLAST_hits"] > 0
    df_genomes["in_IF2"] = df_genomes["IF2_hits"] > 0
    df_genomes["in_IntFilt_IF2"] = df_genomes["IntFilt_IF2_hits"] > 0

    df_genomes.to_csv(f"{outdir}/genomes_hits.csv", index=False)

    # Summary of the comparison (general hits, unique hits and time)
    df_summary = pd.DataFrame(
        [{"method": m,
          "general_hits": hits_summary[m][0],
          "unique_hits": hits_summary[m][1],
          "time_s": times[m]} for m in hits_summary])
    df_summary.to_csv(f"{outdir}/methods_summary.csv", index=False)