# Import libraries 
import subprocess
import shlex
import time
import os
from xml.parsers.expat import errors
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --------Definition of functions
#------------------------ Function to run blastn
def run_blastn(query, output, db, evalue_threshold = 10):
    # FIXME FALTA AÑADIR COSAS DE EVALUES YA ARGS ADDED
    """
    Executes the blastn command with the specified query, output file, and database.

    Args
    ------
    query (str): The path to the query fasta file.
    output (str): The path to the output file where results will be saved.
    db (str): The path to the blast database.

    Return
    ------
    output (str): The path to the output file where results are saved.
    elapsed (float): The time taken to execute the blastn command in seconds.
    """
    # Creates the output directory to avoid errors
    os.makedirs(os.path.dirname(output), exist_ok=True)
    # Blastn command
    blast_cmd = ["blastn", "-query", query, # Query fasta file
                 "-db", db, # Blast database
                 "-out", output, 
                 "-evalue", str(evalue_threshold),
                 "-outfmt", "6"] # Output format 6 (tabular)
    start = time.time() # Start time to measure execution time
    # Execute the command and handle errors
    print(f"Executing: \n{shlex.join(blast_cmd)}")
    try:
        subprocess.run(blast_cmd, 
                       check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        print(f"Error executing blastn:\n{e.stderr}")
        return

    total_time = time.time() - start # End time to measure execution time

    return output, total_time

#------------------------ Function to process tsv files of blastn results
def process_tsv(tsv_files):
    """
    Process the tsv files generated by blastn and returns the dataframes obtained,
    log10 of e-values, bitscores, and labels.
    
    Args
    ------
    tsv_files (dict): A dictionary where keys are the names of the queries and 
                      values are the paths to the corresponding tsv files.

    Return
    ------
    dfs (dict): A dictionary where keys are the names of the queries and
                values are the corresponding pandas dataframes.
    log_data (list): A list of lists containing the -log10 of e-values for each query.
    bitscore_data (list): A list of lists containing the bitscores for each query.
    labels (list): A list of the names of the queries.
    """
    
    # Columns of the tsv files
    columns = ["query_id", "seq_id", "identity", "length", 
               "mismatch", "gapopen", "query_start", "query_end", 
               "seq_start", "seq_end", "Evalue", "BitScore"]
    # Lists and dictionaries to store data
    log_data = []
    bitscore_data = []
    labels = []
    dfs = {}

    for query, path in tsv_files.items(): # For each query and its tsv file
        # Reads the tsv file and converts it into a df
        df = pd.read_csv(path, sep="\t", names=columns) 
        dfs[query] = df # Stores the df in the dictionary of dfs
        evalues = df["Evalue"] # E-values of the query
        # To avoid errors with the log10(0)
        nonzero = evalues[evalues>0] # Stores the non-zero e-values
        if nonzero.empty: min_value = 1e-300 # If all are 0, 1e-300 is used
        else: min_value = nonzero.min()/10 # The minimum value (non-zero) / 10 is used
        evalues = df["Evalue"].replace(0, min_value) # Replace the 0 values
        # Append the values to the corresponding lists
        log_data.append(-np.log10(evalues)) # Calculate log10 of evalues 
        bitscore_data.append(df["BitScore"]) # Append the bitscores to the list
        labels.append(query) # Append the query name to the labels list

    return dfs, log_data, bitscore_data, labels

# Plotting
#------------------------ Function to plot e-values distribution
def plot_evalue(logdata, labels, 
                title = "E-value Distribution", outdir = "results/plots", 
                filename = "evalue_distribution.png"):
    """
    Saves a boxplot of the -log10 of e-values for each query.
    
    Args
    ------
    logata (list): A list of lists containing the -log10 of e-values for each query.
    labels (list): A list of the names of the queries.
    title (str, optional): The title of the plot.
    outdir (str, optional): The directory where the plot will be saved.
    filename (str, optional): The name of the file where the plot will be saved.
    """
    # Creates the output directory to avoid errors
    os.makedirs(outdir, exist_ok=True)
    
    fig, ax = plt.subplots(figsize=(7, 5)) # Creates axes for the plot
    # Creates the boxplot with the data and labels defined
    ax.boxplot(logdata, tick_labels=labels) 
    # Adjusting labels / title:
    ax.set_ylabel("-log10(E-value)") # Y label
    ax.set_title(title) # Title of the plot
    plt.xticks(rotation=20) # Rotates the x-axis labels
    plt.tight_layout() # Adjusts the layout to avoid overlapping
    # Saves the plot
    plt.savefig(os.path.join(outdir, filename)) 

    return

#------------------------ Function to plot bitscore distribution
def plot_bitscore(bitscore_data, labels, 
                  title = "BitScore Distribution", outdir = "results/plots", 
                  filename = "bitscore_distribution.png"):
    """
    Saves a boxplot of the bitscores for each query.
        
    Args
    ------
    bitscore_data (list): A list of lists containing the bitscores for each query.
    labels (list): A list of the names of the queries.
    title (str, optional): The title of the plot.
    outdir (str, optional): The directory where the plot will be saved.
    filename (str, optional): The name of the file where the plot will be saved.
    
    """
    # Creates the output directory to avoid errors
    os.makedirs(outdir, exist_ok=True)

    fig, ax = plt.subplots(figsize=(7, 5)) # Creates axes for the plot
    # Creates the boxplot with the data and labels defined
    ax.boxplot(bitscore_data, tick_labels=labels)
    # Adjusting labels / title:
    ax.set_ylabel("BitScore") # Y label
    ax.set_title(title) # Title of the plot
    plt.xticks(rotation=20) # Rotates the x-axis labels
    plt.tight_layout() # Adjusts the layout to avoid overlapping
    # Saves the plot
    plt.savefig(os.path.join(outdir, filename))

    return

#------------------------ Function to plot e-value thresholds
def plot_evalue_thresholds(dfs, times, evalues = np.logspace(1,-300,200),
                           title = "E-Values thresholds", outdir = "results/plots", 
                           filename = "evalue_thresholds.png"):
    """
    Saves a plot of the number of hits and unique hits for each query at different e-value thresholds.

    Args
    -----
    dfs (dict): A dictionary where keys are the names of the queries and
                values are the corresponding pandas dataframes.
    times (dict): A dictionary where keys are the names of the queries and
                  values are the corresponding execution times.
    evalues (numpy.ndarray, optional): An array of e-values to evaluate.
    title (str, optional): The title of the plot.
    outdir (str, optional): The directory where the plot will be saved.
    filename (str, optional): The name of the file where the plot will be saved.
    """
    # Creates the output directory to avoid errors
    os.makedirs(outdir, exist_ok=True)
    # Range of e-values to evaluate
    range_evalues = evalues
    # Divides figure into two subplots
    fig, axes = plt.subplots(1,2,figsize=(13,5)) # Creates axes for the plot
    col_counter = 0 # Counter to assign colors to each query
    dict_colors = {} # Dictionary to store colors for each query
    colors = ["#963FB0", "#41B883", "#1A6D70"] # Colors for the queries
    for query, df in dfs.items(): # For each query and its df
        dict_colors[query] = colors[col_counter] # Assigns a color to the corresponding query
        col_counter += 1 # Increase the counter
        # Lists to store hits
        n_hits = [] 
        n_unique_hits = []
        for evalue in range_evalues: # For each df, all thresholds are evaluated
            evalues_in_threshold = df["Evalue"] <= evalue # Stores the evalues <= threshold
            n_hits.append(evalues_in_threshold.sum()) # Counts the hits with <= evalue

            seq_ids_in_threshold = df.loc[evalues_in_threshold, "seq_id"] # Extracts the seq_id column
            n_unique_hits.append(seq_ids_in_threshold.nunique()) # Counts unique hits

        # Plots the data of each evalue threshold
        axes[0].plot(range_evalues, n_hits, label = query, color = dict_colors[query])
        axes[1].plot(range_evalues, n_unique_hits, label = query, color = dict_colors[query])

    # Axis, legends and labels:

    for ax in axes: 
        ax.set_xscale("log") # Log x-axis for the plots
        ax.set_xlabel("E-value threshold") # Same labels for x-axis
    # Set y-axis
    axes[0].set_ylabel("Total Hits")
    axes[1].set_ylabel("Unique Hits (seq_id)")

    # List to store the query + its execution time
    labels_for_legend = [] 
    for query, time in times.items():
        labels_for_legend.append(f"{query} - {time:.2f} secs") # Two decimal numbers
    plt.legend(labels = labels_for_legend) # Set legend

    plt.suptitle(title) # Set the principal title

    plt.tight_layout() # Adjusts the layout to avoid overlapping
    # Saves the plot
    plt.savefig(os.path.join(outdir, filename))

    return

# -------- Main code
if __name__ == "__main__":
    # list of queries
    fasta_files = ["data/Int1/Int1.fa", 
                   "data/Int1/Int1_Pc_pattern.fa", 
                   "data/Int1/Int1_no_Pc.fa"]
    all_results = {}
    all_times = {}
    for each_query in fasta_files:
        name = os.path.basename(each_query)

        each_result, each_time = run_blastn(query = each_query, 
                                 output = f"results/1500genomes/blast_{name}.tsv",
                                 db = "data/1500genomes/db/db")
        
        all_results[each_query] = each_result
        all_times[each_query] = each_time


    dfs, evalues, bitscore, labels = process_tsv(all_results)
    outdir = "results/plots/1500genomes"
    plot_evalue(evalues, labels, title = "E-Values distribution - db: 1500 genomes * 5 species (7500)", outdir = outdir)
    plot_bitscore(bitscore, labels, title = "BitScore distribution - db: 1500 genomes * 5 species (7500)", outdir = outdir)
    plot_evalue_thresholds(dfs, all_times, title = "E-Values thresholds - db: 1500 genomes * 5 species (7500)", outdir = outdir)
