# Import libraries 
import subprocess 
import shlex
import os

############## Setup ----------------------------------------
# FIXME: Cuando acabe, hay que adaptar esto a cómo se encuentre finalmente!

current_dir = os.path.dirname(__file__) # __file__ has the path of the current .py 
HattCI_dir = os.path.join(current_dir, "T3_integronfiltering", "HattCI")  # Path where the HattCI executable is located
path_env_variable = os.environ["PATH"]

# Overwrite the PATH variable by adding the HattCI executable
sep = os.pathsep # PATH separator character for each operating system
os.environ["PATH"] = f"{HattCI_dir}{sep}{path_env_variable}" 
# By prepending the HattCI directory, it takes priority over any previously existing ones
#### PATH change only lasts while the script is running
############## ---------------------------------------------

# --------Definition of functions
#------------------------ Function to adapt the output of integron-filtering
def output_integronfiltering(outdir):
    """
    Finds and returns the path of the filtered FASTA file generated by integron_filtering.

    Args
    ------
    outdir (str): Path to the directory with the results of integron_filtering.

    Return:
    ------
    outfile (str): Path to the file with the results of integron_filtering.
    """
    # Files generated by integron_filtering
    results = os.listdir(outdir)
    for each_result in resultaresultsdos_integronfiltering:
        # The file with the genome with context ends in "attC_filtered.fasta"
        if each_result.endswith("attC_filtered.fasta"):
            # Complete path to the file
            outfile = os.path.join(outdir, each_result)
            
            return outfile


def integron_filtering(ruta_genoma, # Ruta al genoma
                       outdir, # Directorio de salida de los resultados
                       modelo_covarianza = os.path.join(actual_dir, "T3_integronfiltering/attCs.cm"), # default, modelo covarianza definido
                       cutoff_bit = 20, # cut-off del bit score del modelo de covarianza (default en el .sh)
                       min_pb = 500, # mínimo tamaño de la secuencia reconocida (default en el .sh)
                       cpu = os.cpu_count() -1 # número de CPUs a utilizar (cambiado, default en el .sh es 1)
                       ):
    """
    Ejecuta el script de filtrado de integrones (attC-screening).

    Args
    ------
    ruta_genoma (str): Ruta al archivo del genoma que se va a procesar.
    outdir (str): Directorio de salida donde se guardarán los resultados.
    modelo_covarianza (str, opcional): Ruta al archivo del modelo de covarianza. 
                                       Por defecto es 'T3_integronfiltering/attCs.cm'.
    cutoff_bit (int/float, opcional): Valor de corte (cut-off) del bit score para el filtrado. 
                                      Por defecto es 20.
    min_pb (int, opcional): Tamaño mínimo en pares de bases de la secuencia reconocida. 
                            Por defecto es 500.
    cpu (int, opcional): Número de CPUs a utilizar para el proceso. 
                         Por defecto usa el total disponible menos 1.

    Return
    ------
    ruta_genoma_filtrado (str): La ruta al genoma filtrado generado si el proceso es exitoso. 
                                Si ocurre un error durante la ejecución de subprocess, devuelve la ruta original del genoma (ruta_genoma).
    """
    # Comando integron_filtering 
    comando_integronfiltering = ["./scripts/T3_integronfiltering/attC-screening.sh", # ruta al .sh
                                 "-m", modelo_covarianza, 
                                 "-i", ruta_genoma,
                                 "-o", outdir,
                                 # Los números deben pasarse como str
                                 "-b", str(cutoff_bit), 
                                 "-l", str(min_pb),
                                 "-t", str(cpu)]

    print(f"Ejecutando: \n {shlex.join(comando_integronfiltering)}")
    try:
        subprocess.run(comando_integronfiltering, 
                       capture_output = True, text = True, check = True) 
    # Capturar la excepción
    except subprocess.CalledProcessError as e:
        print(f"Error al ejecutar integron_filtering :\n{e.stderr}")
        return ruta_genoma # Ruta inicial
    # Función para adaptar la ruta al nuevo genoma filtrado
    ruta_genoma_filtrado = adaptar_dir_integronfiltering(outdir)
    # Control por si no se ha generado el archivo correctamente
    if not ruta_genoma_filtrado:
        print(f"Error al ejecutar integron_filtering")
        return ruta_genoma
    
    return ruta_genoma_filtrado
