# Import libraries 
import os
from T3_0_integronfiltering import integron_filtering
from T3_1_integronfinder import Integron_Finder
from T3_2_Pc import extraer_Pc_gbk

# --------Definition of functions
#------------------------ Function to define flags for genome download (datasets download)
def adjust_path(filename):
    #FIXME: no me convence que esta función esté aquí
    """
    Adapts the directory indicated in the previous script to the one needed to continue the pipeline.
    
    Args
    -------
    filename (str): Directory given in the previous script.

    Return
    -------
    adapted_dir (str): New adapted directory.
    """
    name_of_file = os.path.basename(filename) # Extracts the file name and extension
    name = os.path.splitext(name_of_file)[0] # Extracts only the file name
    # Adds the genome file name and the folders generated when using datasets to the new directory
    dir_adaptado = os.path.join(os.path.dirname(filename), 
                               name, 
                               "ncbi_dataset/data") # Structure generated by datasets
    return adapted_dir

def list_fasta_files(directory):
    """
    Gets the paths of all FASTA files (.fna) stored within the subfolders of a directory.

    Args
    -------
    directory (str): Path of the main directory containing the genome subfolders.

    Returns
    --------
    genome_paths (list): A list with the full paths to each found fasta (.fna) file.
    """
    rutas_genomas = [] # Lista para almacenar la ruta de cada genoma
    carpetas = sorted(os.listdir(directorio)) # lista de carpetas dentro del directorio adaptado
    for carpeta in carpetas: 
        ruta_individual = os.path.join(directorio, carpeta) # Añade la carpeta dentro de la ruta
        # Si se ha descargado correctamente, se genera una nueva carpeta que contiene dentro el genoma
        if os.path.isdir(ruta_individual): 
            archivos_por_carpeta = os.listdir(ruta_individual) # Lista de los archivos de la nueva carpeta
            for archivo in archivos_por_carpeta:
                if os.path.splitext(archivo)[-1] == ".fna": 
                    # Si el archivo concreto se corresponde con un .fasta, se añade a la ruta
                    ruta_archivo = os.path.join(ruta_individual, archivo)
                    rutas_genomas.append(ruta_archivo) # Guarda la ruta individual de cada genoma
    return rutas_genomas

def recorrer_genomas(rutas_genomas,a
                     directorio,
                     flag_integronfiltering = True): # Por defecto se filtra previamente con integron_filtering
    """
    FIXME -> Falta docstring cuando se acabe la función
    """
    dir_parental = directorio.replace("/ncbi_dataset/data", "") # Utiliza como referencia el directorio parental 
    
    for ruta_genoma_individual in rutas_genomas: # Recorre cada archivo con los genomas
        archivo = os.path.basename(ruta_genoma_individual) # Extrae el nombre y extensión del archivo
        acc_genoma = os.path.splitext(os.path.basename(archivo))[0] # Extrae únicamente el nombre del archivo
        # Filtrado vía integron-filtering
        if flag_integronfiltering:
            # Crea una carpeta para los resultados del filtrado, y dentro de esta un subdirectorio con cada genoma         
            directorio_integronfiltering = os.path.join(dir_parental, "results_IntegronFiltering", acc_genoma)
            # Crea el directorio (no error si ya existe)
            os.makedirs(directorio_integronfiltering, exist_ok=True) 
            # Filtrado vía integron-filtering y actualización de la ruta con el genoma filtrado
            ruta_genoma_individual = integron_filtering(ruta_genoma_individual, directorio_integronfiltering)
            # Actualización del accession filtrado
            archivo = os.path.basename(ruta_genoma_individual)
            acc_genoma = os.path.splitext(os.path.basename(archivo))[0]
            
        # Crea una carpeta para los resultados de la búsqueda      
        directorio_integronfinder = os.path.join(dir_parental, "results_IntegronFinder2")
        # Crea el directorio (no error si ya existe)
        os.makedirs(directorio_integronfinder, exist_ok=True) 
        # Ejecución de IntegronFinder2
        archivos_gbk_integronfinder = Integron_Finder(ruta_genoma_individual, 
                                                     acc_genoma, 
                                                     directorio_integronfinder)
        if not archivos_gbk_integronfinder:
            print(f"IntegronFinder2 no ha detectado integrones en el genoma {ruta_genoma_individual}.")
            # FIXME: Habría que borrar aquí algún archivo / directorio para que no de problemas al extraer PCs y clasificar??
            continue
            
        ## EXTRAER INFORMACIÓN SOBRE PCs
        lista_pc = extraer_Pc_gbk(acc_genoma, archivos_gbk_integronfinder)
        for element in lista_pc:
            print(element["secuencia"])
        
        ### falta generar el módulo de clasificación de Pcs!


### FIXME -> Falta arreglar la parte de que no salga Promotor en los .gbk por ejemplo!!!!
### FIXME -> Muchas veces aparece además el mensaje de: 
# "No se ha podido procesar el genoma results/pruebas_T2/kpn/results_IntegronFiltering/GCF_001663295.1_ASM166329v1_genomic/GCF_001663295.1_ASM166329v1_genomic.attC_filtered.fasta por IntegronFinder2"


# EJEMPLOS USADOS:


path=ajustar_directorio_T2("results/pruebas_T2/kpn.zip")
# genom = acceder_archivos_fasta(path)
# recorrer_genomas(genom, path)

# Prueba con otra especie para ver si funciona bien IntegronFinder2
# con flag de filtrado true
##----Acinetobacter baumannii
file01 = "results/pruebas_IntegronFinderCheck/EC.zip"
path01 = ajustar_directorio_T2(file01)
genomas = acceder_archivos_fasta(path01)
recorrer_genomas(genomas, path01)

##----Escherichia coli
file02 = "results/pruebas_IntegronFinderCheck/EC.zip"
# path02 = ajustar_directorio_T2(file02)
# genomas02 = acceder_archivos_fasta(path02)
# recorrer_genomas(genomas02, path02)

# con flag de filtrado false
##----Acinetobacter baumannii
# recorrer_genomas(genomas, path01, flag_integronfiltering=False)

##----Escherichia coli
# recorrer_genomas(genomas02, path02, flag_integronfiltering=False)
