# Import libraries 
import os
import glob
from T3_0_clusters import cluster_genomes
from T3_1_integronfiltering import integron_filtering
from T3_1_integronfinder import Integron_Finder
from T3_2_Pc import extraer_Pc_gbk

# --------Definition of functions
#------------------------ Function to define flags for genome download (datasets download)
def adjust_path(filename):
    #FIXME: no me convence que esta función esté aquí
    """
    Adapts the directory indicated in the previous script to the one needed to continue the pipeline.
    
    Args
    -------
    filename (str): Directory given in the previous script.

    Return
    -------
    adapted_dir (str): New adapted directory.
    """
    name_of_file = os.path.basename(filename) # Extracts the file name and extension
    name = os.path.splitext(name_of_file)[0] # Extracts only the file name
    # Adds the genome file name and the folders generated when using datasets to the new directory
    adapted_dir = os.path.join(os.path.dirname(filename), 
                               name, 
                               "ncbi_dataset/data") # Structure generated by datasets
    return adapted_dir

def list_fasta_files(directory):
    """
    Gets the paths of all FASTA files (.fna) stored within the subfolders of a directory.

    Args
    -------
    directory (str): Path of the main directory containing the genome subfolders.

    Returns
    --------
    genome_paths (list): A list with the full paths to each found fasta (.fna) file.
    """
    # Check genome files
    if not os.path.isdir(directory):
        raise FileNotFoundError(f"The directory {directory} was not found.")

    # Set the genome file path pattern
    genomes_path = os.path.join(directory, "*", "*.fna")
    # Use glob to correctly intepret the wildcard (*)
    genomes_path_glob = sorted(glob.glob(genomes_path))
    
    return genomes_path_glob

def recorrer_genomas(rutas_genomas,
                     directorio,
                     flag_integronfiltering = True): # Por defecto se filtra previamente con integron_filtering
    """
    FIXME -> Falta docstring cuando se acabe la función
    """
    dir_parental = directorio.replace("/ncbi_dataset/data", "") # Utiliza como referencia el directorio parental 
    
    for ruta_genoma_individual in rutas_genomas: # Recorre cada archivo con los genomas
        archivo = os.path.basename(ruta_genoma_individual) # Extrae el nombre y extensión del archivo
        acc_genoma = os.path.splitext(os.path.basename(archivo))[0] # Extrae únicamente el nombre del archivo
        # Filtrado vía integron-filtering
        if flag_integronfiltering:
            # Crea una carpeta para los resultados del filtrado, y dentro de esta un subdirectorio con cada genoma         
            directorio_integronfiltering = os.path.join(dir_parental, "results_IntegronFiltering", acc_genoma)
            # Crea el directorio (no error si ya existe)
            os.makedirs(directorio_integronfiltering, exist_ok=True) 
            # Filtrado vía integron-filtering y actualización de la ruta con el genoma filtrado
            ruta_genoma_individual = integron_filtering(ruta_genoma_individual, directorio_integronfiltering)
            # Actualización del accession filtrado
            archivo = os.path.basename(ruta_genoma_individual)
            acc_genoma = os.path.splitext(os.path.basename(archivo))[0]
            
        # Crea una carpeta para los resultados de la búsqueda      
        directorio_integronfinder = os.path.join(dir_parental, "results_IntegronFinder2")
        # Crea el directorio (no error si ya existe)
        os.makedirs(directorio_integronfinder, exist_ok=True) 
        # Ejecución de IntegronFinder2
        archivos_gbk_integronfinder = Integron_Finder(ruta_genoma_individual, 
                                                     acc_genoma, 
                                                     directorio_integronfinder)
        if not archivos_gbk_integronfinder:
            print(f"IntegronFinder2 no ha detectado integrones en el genoma {ruta_genoma_individual}.")
            # FIXME: Habría que borrar aquí algún archivo / directorio para que no de problemas al extraer PCs y clasificar??
            continue
            
        ## EXTRAER INFORMACIÓN SOBRE PCs
        lista_pc = extraer_Pc_gbk(acc_genoma, archivos_gbk_integronfinder)
        for element in lista_pc:
            print(element["secuencia"])
        
        ### falta generar el módulo de clasificación de Pcs!


### FIXME -> Falta arreglar la parte de que no salga Promotor en los .gbk por ejemplo!!!!
### FIXME -> Muchas veces aparece además el mensaje de: 
# "No se ha podido procesar el genoma results/pruebas_T2/kpn/results_IntegronFiltering/GCF_001663295.1_ASM166329v1_genomic/GCF_001663295.1_ASM166329v1_genomic.attC_filtered.fasta por IntegronFinder2"


# EJEMPLOS USADOS:

if __name__ == "__main__":
    # PRUEBA CON CLUSTERIZADO
    file = "results/T2_check/Deinococcus.zip"
    adapted_file = adjust_path(file)
    genomes_files = list_fasta_files(adapted_file)
    clustered_files = cluster_genomes(genomes_files, adapted_file)


    # PRUEBA SIN CLUSTERIZADO
    # file = "results/T2_check/Deinococcus.zip"
    # adapted_file = adjust_path(file)
    # genomes_files = list_fasta_files(adapted_file)
    # recorrer_genomas(genomes_files, adapted_file, flag_integronfiltering=True)
